apache/infrastructure-puppet

Puppetfile, data/nodes/devops.apache.org.yaml, data/ubuntu/1404.yaml, modules/fail2ban_asf/files/fail2ban/conf/action.d/asf999-log.conf, modules/fail2ban_asf/files/fail2ban/conf/filter.d/sshd-asf999.conf, modules/fail2ban_asf/manifests/config.pp
@markt-asf requested to add asf999 log in logging.
This adds the email notification that asf999 has logged into a host.
=> Add Asf999 logging to fail2ban

data/nodes/whimsy-vm2.apache.org.yaml, modules/whimsy_server/manifests/init.pp, modules/whimsy_server/templates/procmailrc.erb
Delivers email addressed to secretary@whimsy-vm2.apache.org directly to the secmail application.
Also drops the hardcoded uid for apmail (per request by @stumped2), and symlinks the rvm wrappers for ruby to the /usr/local/bin directory.
=> Whimsy delivery

modules/whimsy_server/manifests/init.pp
The ones that remain are due to using "old-style iteration":
https://docs.puppetlabs.com/puppet/latest/reference/lang_iteration.html#old-style-iteration-with-defined-types
modules/whimsy_server/manifests/init.pp - ERROR: whimsy_server::ruby::symlink not in autoload module layout on line 75
modules/whimsy_server/manifests/init.pp - ERROR: whimsy_server::rvm::symlink not in autoload module layout on line 84
modules/whimsy_server/manifests/init.pp - WARNING: defined type defined inside a class on line 75
modules/whimsy_server/manifests/init.pp - WARNING: defined type defined inside a class on line 84
=> fix most lint warnings

modules/whimsy_server/manifests/cronjobs.pp, modules/whimsy_server/manifests/init.pp
Puppet will only set the ownership of the directory and log; this
would be sufficient for a new install but at the moment there is
existing content and an existing root cron job doing updates.
I've done:
chown -R whimsysvn:whimsysvn /srv/svn
... but if the cronjob kicks off before this puppet update is applied,
the whimsysvn cronjob may fail due to lacking permissions on files
created by root
=> change ownership of svn from root to whimsysvn

data/nodes/whimsy-vm2.apache.org.yaml
I haven't been able to test this yet, but I believe it will resolve issues with sending email from the new Whimsy VM. The change is based on the same line from another node in this directory.
=> add TLS for SMTP

modules/subversion_server/files/authorization/asf-authorization-template
Not used for authorization - just to make http://people.apache.org/phonebook.html?podling=commonsrdf
=> Add commonsrdf podling committers

modules/gitwcsub/files/app/gitwcsub.py
... because pull barfs when faced with forced pushes; assume the source
is the canonical master and there is no local changes that need to be
retained.
=> replace pull with fetch+reset

data/nodes/whimsy-vm2.apache.org.yaml, data/nodes/whimsy-vm3.apache.org.yaml, modules/whimsy_server/manifests/init.pp, modules/whimsy_server/manifests/procmail.pp
Tested with puppet kitchen
Change has already been made to the directory structure on both whimsy-vm2 and
whimsy-vm3:
root@whimsy-vm2:~# ls -l /srv /x1/srv
lrwxrwxrwx  1 root root    7 May  9 14:50 /srv -> /x1/srv
/x1/srv:
total 36
drwxr-xr-x  2 www-data  www-data  4096 May  1 12:57 agenda
drwxr-xr-x  3 whimsysvn whimsysvn 4096 Mar  9 17:30 git
drwx------  2 www-data  www-data  4096 May  7 23:03 gpg
drwxr-xr-x  5 www-data  www-data  4096 May  1 06:34 mail
drwxr-xr-x  3 apmail    apmail    4096 Jan  8 19:33 mbox
drwxr-xr-x  4 www-data  www-data  4096 Mar 17 16:04 secretary
drwxr-xr-x  2 apmail    apmail    4096 Mar 16 04:11 subscriptions
drwxr-xr-x 23 whimsysvn whimsysvn 4096 May  1 06:34 svn
drwxr-xr-x  9 root      root      4096 May  5 13:47 whimsy
root@whimsy-vm3:~# ls -l /srv /x1/srv …
=> move /srv to /x1

modules/subversion_server/files/authorization/asf-authorization-template
Good Day!
Could I kindly ask review this PR?
We recently add new committer and It just for http://people.apache.org/phonebook.html?podling=quarks
(I tried to add this via git1-us-west.apache.org but it failed. I could do this 1 month ago but not now.
So I create PR with github. Please tell me if this is not standard solution)
[hadoop@ip-10-0-0-126 infrastructure-puppet]$  git push origin quarks
Username for 'https://git1-us-west.apache.org': cazen
Password for 'https://cazen@git1-us-west.apache.org': 
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 578 bytes | 0 bytes/s, done.
Total 7 (delta 6), reused 0 (delta 0)
remote: You are not authorized to edit this repository.
remote: 
remote: auth check …
=> Add Apache Quarks(incubating) committers

modules/subversion_server/files/authorization/asf-authorization-template
Add Toree Podling committers to asf-authorization-template to enable publishing Toree website that is using svn-pub-sub.
=> Add Toree podling to asf-authorization-template

data/nodes/comdev-vm.apache.org.yaml
I'm taking a look at https://issues.apache.org/jira/browse/COMDEV-201; but before I do I'm trying to build the vm on my own for testing purposes.  I came across two issues.  For the docker one, I don't see how the current definition could build at all; for the mod-lua one I can only presume that this was initially installed outside of puppet.
=> comdev bootstrap

modules/subversion_server/files/authorization/asf-authorization-template
After creating the Toree podling group, there is still a need to provide the access level to the group.
=> Enable write access to Toree podling group

data/nodes/ghmon-vm.apache.org.yaml
next step is letsencrypt/certbot and verifying the ability to send mail
Related svn commit 993135 to dns/zones.   sudo rndc reload requested as
it will be needed before letsencrypt deployment can proceed.
=> rough in apache + postfix

modules/subversion_server/files/authorization/asf-authorization-template
Current data in LDAP:
$ ldapsearch -x -LLL cn=db-jdo -b ou=auth,ou=groups,dc=apache,dc=org member
dn: cn=db-jdo,ou=auth,ou=groups,dc=apache,dc=org
member: uid=brazil,ou=people,dc=apache,dc=org
member: uid=brianm,ou=people,dc=apache,dc=org
member: uid=btopping,ou=people,dc=apache,dc=org
member: uid=clr,ou=people,dc=apache,dc=org
member: uid=dain,ou=people,dc=apache,dc=org
member: uid=ebengston,ou=people,dc=apache,dc=org
member: uid=geirm,ou=people,dc=apache,dc=org
member: uid=madams,ou=people,dc=apache,dc=org
member: uid=mbo,ou=people,dc=apache,dc=org
member: uid=mcaisse,ou=people,dc=apache,dc=org
member: uid=mzaun,ou=people,dc=apache,dc=org
member: uid=pcl,ou=people,dc=apache,dc=org
member: uid=andyj,ou=people,dc=apache,dc=org
member: uid=tilmannz,ou=people,dc=apache,dc=org
=> Convert auth for db-jdo to use LDAP

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/pit-authorization-template
Convert derby to use LDAP auth group: cn=db-derby,ou=auth,ou=groups,dc=apache,dc=org
You can verify that the auth group is set up using either of the following:
* `ldapsearch -x cn=db-derby`
* https://whimsy.apache.org/roster/group/db-derby
=> convert derby auth list to db-derby auth group

modules/subversion_server/files/authorization/pit-authorization-template
We use a subdir of /repos/private/pmc/httpd for security@httpd. We
allow non-PMC members to participate, but need to punch a hole in current
asf auth for it.
=> allow non-pmc httpd security@ access

modules/buildbot_asf/files/create-ooo-snapshots-index.sh
Using a generic name instead of the actual release branch name (AOO413, AOO414, etc.) there is no need to update this file for every new release.
=> Use a generic name for the current release branch

modules/gump_server/manifests/init.pp
git and subversion get added via classes inherited from `ubuntu/14.04`
=> INFRA-12291 remove conflicting packages from gump_server

data/nodes/vmgump-vm3.apache.org.yaml
Sending email from vmgump still doesn't work, likely because it is not using the relay that has been configured to allow access with #140
=> INFRA-12291 change relay host to the one configured in #140

modules/gump_server/manifests/init.pp
this tells vmgump-vm3's mono installation to import the cert-roots trusted by mozilla, this is necessary for nuget's https connections to get established properly.
=> vmgump's mono needs additional certs in truststore

data/nodes/proxy1-us-west.apache.org.yaml, data/nodes/proxy2-lw-us.apache.org.yaml, data/nodes/proxy2-us-west.apache.org.yaml, data/nodes/proxy3-us-west.apache.org.yaml, data/nodes/tools-vm.apache.org.yaml
It's misleading to prompt "PMC Members Only" when the requirement is merely ASF committership
=> Clarify the LDAP membership requirement

modules/subversion_server/files/authorization/asf-authorization-template
Following ids fixed:
szetszwo, mayank, ddas, gtcarrera9
=> Fixed committer ids for ratis.

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/pit-authorization-template, modules/subversion_server/files/scripts/authorization/gen_asf-authorization.pl
look for ";attr=" within {ldap:} sections, and extract attribute name
if this string is present; otherwise default to memberUid,member for
backwards compatibility.
A single example of this new syntax is included in this commit.
The plans are to shortly make use of this to move PMC authorizations to
an owner attribute.
=> allow LDAP attribute to be specified in authorization templates

data/nodes/svn01-us-west.apache.org.yaml, modules/subversion_server/manifests/init.pp
This switches from CGI to Gunicorn via proxy.
Puppet will check if gunicorn is running (the ps|grep bit), and if not, launch it in daemon mode.
This also addresses some ViewVC aliases we had left out.
=> Change viewVC to run via gunicorn

modules/gitbox/files/asfgit/hooks/sync.py
If a force push is required, use -f to push to github with force.
Ref: INFRA-14039
Otherwise, do a normal push.
=> use force if rewrite is detected (and allowed)

modules/subversion_server/files/authorization/pit-authorization-template
This time get the directory correct.
reverts https://github.com/apache/infrastructure-puppet/commit/613ef169d508867ae2ddc165204ecf5ee3ecef21
=> enable whimsy to submit subreqs on behalf of committers

modules/ldapserver/templates/slapd.conf.erb
See: http://www.openldap.org/doc/admin24/access-control.html#What%20to%20control%20access%20to
"There are two special pseudo attributes entry and children. To read (and hence
return) a target entry, the subject must have read access to the target's entry
attribute. To perform a search, the subject must have search access to the
search base's entry attribute. To add or delete an entry, the subject must have
write access to the entry's entry attribute AND must have write access to the
entry's parent's children attribute. To rename an entry, the subject must have
write access to entry's entry attribute AND have write access to both the old
parent's and new parent's children attributes."
So note that this will grant the secretary access to delete an entry.  There is
no intent to make use of …
=> baby steps: allow secretary to create people in LDAP

data/nodes/whimsy-vm4.apache.org.yaml
Whilst the existing redirect works, it would need to be changed if a new instance is created and made current.
=> Redirect to current so still works when transitioning to new instance

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/pit-authorization-template
Removing auth for blur & horn as they have retired:
http://incubator.apache.org/projects/#retired
=> blur, horn have retired

modules/subversion_server/files/authorization/pit-authorization-template
Obvious syntax error:
https://github.com/apache/infrastructure-puppet/blob/4511dd63e3725ba1ba0f55031789f64d16bd719c/modules/subversion_server/files/authorization/pit-authorization-template#L1102
Line should not start with '+'
=> Syntax error - remove leading '+'

data/ubuntu/1404.yaml, data/ubuntu/1604.yaml
base yaml now writes a file (disk.yaml) and then restarts the datadog-agent service if the file has been changed.
=> Datadog Disk monitoring 

modules/subversion_server/files/authorization/asf-authorization-template
This will allow the the following to be deleted:
https://svn.apache.org/repos/asf/incubator/blur/
It only contains obsolete site data.
The following has already been removed, so the auth entry is useless:
https://svn.apache.org/repos/asf/incubator/horn/
=> Blur/Horn retired; allow SVN sites to be dropped

data/nodes/tools-vm.apache.org.yaml, modules/jenkins_node_monitor/files/jnm.py, modules/jenkins_node_monitor/manifests/init.pp, modules/jenkins_node_monitor/templates/settings.cfg.erb
New module that pulls node and status from builds.a.o and pushes that data to DataDog as a custom service check.
=> Jenkins Node Monitor

modules/subversion_server/files/authorization/asf-authorization-template
httpcomponents site is still svnpubsub
=> httpcomponents site is still svnpubsub

data/nodes/ofbiz-vm2.apache.org.yaml
there is no 'cron_before_command', which is breaking the puppet run.
=> there is no 'cron_before_command', which is breaking the puppet run.

data/ubuntu/1404.yaml, data/ubuntu/1604.yaml
Adding two excludes as Docker throws a ton of warnings into syslog.
=> Adding two excludes as Docker throws a ton of warnings into syslog.

modules/mboxer/files/tools/archive.py
Unfortunately this bug was not spotted earlier.
=> Oops: need to quote back reference introducer

data/nodes/snappy1.apache.org.yaml, data/nodes/snappy2.apache.org.yaml
Removing vhosts_asf::vhosts class as it's no longer needed and causing errors
=> Removing vhosts_asf::vhosts class as it's no longer needed and causing errors

modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
Add Symlinking for JDK9 to latest1.9 - Keeping 1.8 as latest for the time being.
=> Add Symlinking for JDK9 to latest1.9 - Keeping 1.8 as latest for the time being.

data/nodes/mbox-vm.apache.org.yaml
=> bump mbox size limit to 4GB

modules/mboxer/files/tools/archive.py
If the script fails, all the output will be written to syslog.
At present the output does not identify the message; add some context to make it easier to track errors
=> Log more on error

modules/build_slaves/manifests/init.pp
https://github.com/apache/infrastructure-puppet/blob/deployment/data/ubuntu/1604.yaml#L382 are only 'ensure => installed', I think this should be latest.
=> ensure latest for all distro packages in jenkins

modules/mboxer/files/tools/archive.py
As per the comments, at present the RE can match:
for <mmm@apache.org> from <nnn@apache.org>;
=> Don't use greedy REs as they match too much

data/nodes/whimsy-vm4.apache.org.yaml
Two problems:
1) I forgot about the need to do puppet escaping %%{}{...}
2) This addition is placed in the wrong part of the config file; it needs
to go after the generated board agenda authentication.
Reverting until I can properly address both problems.
This reverts commit d786e2e6d1f87b636856e53e13256d5ebd66925d.
=> Revert "prep for service workers"

data/nodes/jenkins-master.apache.org.yaml
Changing mail relay on jenkins-master from mail.a.o to mailrelay1-us-west.a.o
=> Changing mail relay on jenkins-master from mail.a.o to mailrelay1-us-west.a.o

modules/mboxer/files/tools/archive.py
Added --lid option to allow list mail address to be specified
e.g. for aliases which don't have a List-Post or where the List-Post is incorrect
=> INFRA-15193 - mboxer/archive.py does not work for mail aliases

modules/mboxer/manifests/init.pp
These archive aliases are to allow mail aliases such as secretary@ to be archived.
There is also a test alias
=> Add alias archive endpoints for email aliases

modules/loggy/files/loggy.py
this NEEDS to be a string, or ES will try to analyze it as a date
=> this NEEDS to be a string, or ES will try to analyze it as a date

modules/mboxer/manifests/init.pp
Sorry, just realised the vp alias archives are supposed to be restricted
=> vp-* should be restricted

data/nodes/wicket-vm.apache.org.yaml
docker images are rewritten to use ROOT.war, no redirect neccessary any more. INFRA-15525
=> docker images are rewritten to use ROOT.war, no redirect neccessary any more. INFRA-15525

Puppetfile, environments/windows/modules/jenkins_slave_windows/manifests/init.pp
Adding puppetlabs-registry to Puppetfile and then using it to enable long file paths on the Jenkins Windows node.
=> Adding puppetlabs-registry to Puppetfile and then using it to enable long file paths on the Jenkins Windows node.

modules/gitbox/files/asfgit/git_multimail.py
set a default max cap of diff lines to 10k for multimail
=> set a default max cap of diff lines to 10k for multimail

.travis.yml, bin/lint.sh
.travis.yml installs the puppet dependencies and then just runs the bin/lint.sh script
lint.sh gets the most recent commit and files changes in that file, and then reports the linting problems
future work will report to the ticket the list of files and linting errors
=> add .travis.yml for linting as well as lint.sh

modules/gitbox/files/asfgit/auth.py
this change might not be necessary for gitbox, but i believe it was the cause of the problem we had with impala defaulting to old LDAP groups because it checks old groups first, so anyone who is getting added to the new groups isn't necessarily getting back ported to the old group
maybe I just need a sanity check :)
=> use new group DN for git auth before defaulting to old

modules/loggy/manifests/init.pp
another option would be to replace the system install of python-setuptools (in 14/1604.yaml) with a pip installed version but that might be too far reaching
so instead we could just add an ensure => latest to base or in the yamls for 1404/1604
=> old version of setuptools is causing a failure to install loggy

data/nodes/gitbox.apache.org.yaml
old school TLS for gitbox for now
=> old school TLS for gitbox for now

data/ubuntu/1404.yaml, data/ubuntu/1604.yaml
build-essential is provided in the same attribute and python-dev is provided by `python::dev: true`
=> add python3-dev to jenkins build nodes

data/nodes/jenkins-beam1.apache.org.yaml, data/nodes/jenkins-beam2.apache.org.yaml, data/nodes/jenkins-beam3.apache.org.yaml, data/nodes/jenkins-beam4.apache.org.yaml, data/nodes/jenkins-beam5.apache.org.yaml, data/nodes/jenkins-beam6.apache.org.yaml, data/nodes/jenkins-beam7.apache.org.yaml, data/nodes/jenkins-beam8.apache.org.yaml, modules/build_slaves/manifests/kube.pp
This installs kubectl with an exec, creating the executable and only running once.  This can be added in yaml (as committed) to add to any node as incorporating an entire kubernetes puppet module is overkill.  While the exec isn't ideal, for this type of binary installation it makes sense.
=> install kubectl on jenkins-beam{1..8}

data/nodes/whimsy-vm4.apache.org.yaml
needed for debugging with Firefox.  Source is already posted on github, so no
security concerns are introduced by this change..
=> allow original source to be downloaded without authentication

data/nodes/tools-vm.apache.org.yaml
=> move broken infra site links to point at selfserve until we can move the

modules/gitbox/manifests/init.pp
the extra file{} block for /x1/gitbox/matt blocks the recurse of files
in /x1/gitbox/matt from puppet, so puppet updates don't get applied.
=> remove extra matt block

data/nodes/mailprivate-vm.apache.org.yaml
As per INFRA-15650, use RequireAny to group PMC and ASF members
Note that there is no need to change the definition in the gen-httpdconfig.sh file, as that is no longer used (it was intended for dist.a.o)
=> Allow ASF members to view /pmc/ URLs

data/nodes/mailprivate-vm.apache.org.yaml
Unfortunately PMC access stopped working when I extracted the shared attributes.
I'm hoping that explicitly setting AuthLDAPGroupAttributeIsDN will fix this.
=> Explicitly set AuthLDAPGroupAttributeIsDN On

data/nodes/mailprivate-vm.apache.org.yaml
This needs more work to enable the AuthzProviderAlias section.
However it should be usable as is (except ASF members won't get access to the /pmc area).
But at least PMC members will have access to the /pmc area
=> Try again to fix INFRA-15650

modules/subversion_server/files/authorization/asf-authorization-template
Drop unused tac-pmc and security-pmc references from asf-auth
=> Asf auth drop tac

modules/subversion_server/files/authorization/asf-authorization-template
@gmcdonald I don't think you can use parentheses in the pathname like that.
=> archetypes with an s goes ro INFRA-16087

modules/mail_private/manifests/init.pp
Easier to read, and no need for the lint exclusion
=> cron environment is clearer as an array

modules/mail_archives/manifests/init.pp
There is one fix: crontab treats % as a new-line, which means that the job is not getting the correct parameters.
This can be seen from the Kibana entries which show a truncated parameter for the generate-sitemap job. It's not clear whether any errors are generated by the script
The other changes are cosmetic:
- consistent variable usage
- use arrays for cron environment
=> Various fixes to mail-archives init.pp

modules/mail_private/templates/refresh-index.pl.erb
Note that this error only showed up as a message in mail.log
=> gzcat => zcat

data/nodes/themis.apache.org.yaml, data/nodes/tlp-eu-west.apache.org.yaml
This change only affects oltu.apache.org [recently retired] ;
because (only) /www/attic.apache.org/flagged/oltu.apache.org/ exists.
To test, visit http://oltu.apache.org/
=> += output filter for atticked TLPs

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/asf-mailer.conf, modules/subversion_server/files/authorization/pit-authorization-template
Retire Oltu. In addition to the patch provided on INFRA-16309 I also removed the oltu ldap group entries for asf and pit auth files.
=> Retire Oltu. In addition to the patch provided on INFRA-16309 I also removed the oltu ldap group entries for asf and pit auth files.

modules/subversion_server/manifests/init.pp
* add cron job for the new python-based authz generation
* remove the "ldap_change" authz step, as it is redundant with the
other generation step
note: the old perl-based "template_commit" generate is still running
and creates proper files (the new py step creates *.alt for now)
=> alter cron jobs for authz generation

data/nodes/mysql1-ec2-va.apache.org.yaml, modules/mysql_asf/manifests/backup.pp, modules/mysql_asf/templates/dbsave_mysql.sh.erb
add a flaggable ability to push mysql db dumps offsite to bai via rsync.
add stunnel_asf as a dependency to mysql_asf::backup. This shouldn't
affect machines that don't need it, but is necessary to make offsite
backups use only a single flag. nb: this will also require further
commits/changes to enable the backup on bai and eyaml to add the rsync
passwords.
=> mysql rsync

modules/mysql_asf/manifests/backup.pp
require, not include for stunnel_asf class. we need the class
instantiated.
=> mysql-rsync

modules/loggy/manifests/init.pp
these pips are not used by loggy.
=> these pips are not used by loggy.

Puppetfile
Moving datadog_agent to github.com/apache/puppet_datadog_agent in order to make changes to DD agent 1.7.0 which is EOL.
=> Moving datadog_agent to github.com/apache/puppet_datadog_agent in order to make changes to DD agent 1.7.0 which is EOL.

data/nodes/svn01-us-west.apache.org.yaml
Zeppelin approach the 1GB limit for then bin-all file
=> Zeppelin approach the 1GB limit for then bin-all file

modules/qmail_asf/manifests/init.pp
Add dot-forward package, replaces qmail-contrib as supplied by fbsd
=> Add dot-forward package, replaces qmail-contrib as supplied by fbsd

modules/mail_archives/files/scripts/update-index
Currently the script is creating empty files and links every month.
See for example:
-rw-rw-r-- 1 modmbox modmbox 0 May 28 18:36 /x1/mail-archives.apache.org/mod_mbox/harmony-dev/201805
=> Don't create the files unnecessarily

data/roles/tlpserver.yaml
AFAICT it does not make sense to only support www-us for the (shared) tlpserver.
Applying this should fix the broken www-eu.a.o URLs.
=> Treat www-eu and www-us equally

modules/jenkins_asf/manifests/init.pp
If there is a good reason to use www-eu rather than www, it should be documented in the scrip
=> Use generic host

data/nodes/netbeans-vm.apache.org.yaml
Hello,
for netbeans-vm.apache.org we need Apache2 logfiles to rotate daily so we can do some ad-hoc processing and analysis of daily logs.
=> Adding logrotate config for Apache2 on netbeans-vm.apache.org

modules/subversion_server/files/authorization/asf-authorization-template
setting svn repo for Turbine Maven Archetypes to read only INFRA-16437
=> setting svn repo for Turbine Maven Archetypes to read only INFRA-16437

data/ubuntu/ubuntu_1604.yaml, modules/tz16_asf/manifests/init.pp
force tz to UTC on ubuntu 16 boxes, as this doesn't work properly in
puppet 3.
=> INFRA-16735

modules/subversion_server/files/authorization/pit-authorization-template
The project.members is the same as the unix group comdev, so use it to be consistent with other projects
=> Standardise on project for comdev

modules/mail_archives/files/scripts/site-index.py, modules/mail_archives/files/scripts/update-index, modules/mail_archives/manifests/init.pp
Make the script more versatile by providing the output name as a parameter.
=> INFRA-16691 - Provide name as parameter

data/common.yaml
lot of email apparently going missing in spamd that we need to receive here...so, fingers crossed
=> Whitelist planners@apachecon to deal with missing email

data/nodes/whimsy-vm4.apache.org.yaml
=> Typo - align with existing paths

modules/jenkins_asf/manifests/init.pp
due to multiple nodes (still with 360gb disks) alerting, I think running this daily would be better, since we're only looking for 31 day retention anyways
=> change jenkins cleanup script to run daily

modules/customfact/lib/facter/customfact.rb
should solve problem with GCE beam nodes not preserving hostnames
=> extend jenkins role regex to default GCE names for beam nodes

modules/cwiki_asf/templates/cleanup-tomcat-logs.sh.erb
Lets make sure the logs dir we are changing into actually exists, otherwise 'find .' along with 'exec rm' could have unintended side effects.
=> Ensure log dir exists before rm cleanup

modules/gitwcsub/files/config/gitwcsub.cfg
Beam is updating its infrastructure for generating and publishing
website content. Motivation and details at: https://s.apache.org/beam-site-automation
Website sources are now hosted at: https://github.com/apache/beam/tree/master/website
Website generated HTML is now hosted at: https://github.com/apache/beam/tree/asf-site
Release-based javadocs and pydocs are now hosted at: https://github.com/apache/beam-site/tree/release-docs
=> [BEAM-4499] Update Beam website publising

data/nodes/svn01-us-west.apache.org.yaml
Since we upped the general limits to dist, a bunch of the old rules no longer serve any meaningful purpose, and should just be canned.
=> Consolidation: remove dist bumps that no longer make sense

modules/gitwcsub/files/config/gitwcsub.cfg
Makes the checkout directory for the camel-website.git:asf-site branch
be `/www/camel.apache.org/content/staging` as the current site has a
`/content` which is matched by rewrite rules. As suggested by Daniel
Gruno[1]
[1] https://issues.apache.org/jira/browse/INFRA-15969?focusedCommentId=16668569#comment-16668569
=> Change camel-website checkout directory path

modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/init.pp
removing gradle 3.5, 4.3.1, and 4.4.1. Adding 4.6, 4.7, 4.8.1, 4.9, 4.10, and 4.10.2 to Jenkins and Buildbot slaves
=> removing gradle 3.5, 4.3.1, and 4.4.1. Adding 4.6, 4.7, 4.8.1, 4.9, 4.10, and 4.10.2 to Jenkins and Buildbot slaves

modules/subversion_server/files/authorization/generate-dist-authorization
The old LDAP groups are not needed any more.
In any case, the generated entries will be overridden by the new groups
Also the script does not handle empty member/owner groups properly - it fails to provide the trailing newline.
e.g. gearpump-pmc is empty and results in the following invalid output:
gearpump-pmc=geode=.....
geode-pmc=...
The geode auth only works at present because of the duplicates generated by the old-style groups.
=> Old LDAP no longer useful; fix bug for empty owner

modules/git_mirror_asf/files/bin/update-index.sh
This addresses the permission issues on git.a.o that keeps migrated git repos around even though they shouldn't be there, by, as git user, punting them to a hidden dir.
=> Punt migrated git repos to hidden folder

environments/windows/modules/jenkins_slave_windows/manifests/params.pp
adding geckodriver 0.18.0 and 0.23.0 to the Jenkins Windows nodes
=> adding geckodriver 0.18.0 and 0.23.0 to the Jenkins Windows nodes

modules/subversion_server/files/authorization/asf-mailer-dist.conf
Replace old list name (alias) with actual list name
This might help stop duplicate emails for commits to /META arriving at commits@
=> infrastructure-cvs@apache.org => commits@infra.apache.org

modules/qmail_asf/files/apmail/bin/subreq.py
Fixes bugs discovered while investigating INFRA-17958
- missing 'op' variable in welcome method
- pathname concatenation
Also corrects message Subject and body for unsub requests
=> Infra 17958

modules/gitbox/files/hooks/post-receive, modules/gitbox/files/hooks/update
os.listdir is documented to return files in arbitrary order.
However hooks must be processed in alpha order, so the names must be sorted.
=> Hooks must be processed in alpha order

modules/subversion_server/files/authorization/pit-authorization-template
remove unused pit-auth for security-pmc
if this is ever needed in the future it can be recreated using the
current ou=project attr=owner format.
=> INFRA-16188

modules/httpd_rate_limiter/manifests/init.pp, modules/httpd_rate_limiter/templates/rate-limit.lua.erb
Defaults to nothing for now, we can adjust and add a default later
=> Allow rate-limiter to whitelist IPs or CIDR blocks

modules/gitwcsub/files/config/gitwcsub.cfg, modules/subversion_server/files/authorization/asf-authorization-template, modules/svnwcsub/files/svnwcsub.conf
calcite was moved from svn to gitbox, making changes for gitwcsub
=> calcite was moved from svn to gitbox, making changes for gitwcsub

modules/selfserve_portal/files/populate-properties.sh
Add locking so we dont run multiple migrations at once. Clean the output dir prior to a new migration attempt.
=> Add locking so we dont run multiple migrations at once. Clean the output dir prior to a new migration attempt.

modules/selfserve_portal/files/sync-moin-all.sh, modules/selfserve_portal/files/sync-moin-project.sh
Update the rsync scripts to remove files not on the source, and files in the exclude list.
This avoids having to start again if the exclude file list is changed or if a project tidies up their Moin Wiki before starting a transfer
=> Delete excluded files from dest

data/nodes/mbox-vm.apache.org.yaml
Getting error from mbox-vm:
@ERROR: access denied to private from UNKNOWN (10.10.3.175)
rsync error
=> Wrong local IP for mailprivate-vm2

data/nodes/whimsy-vm4.apache.org.yaml
This is intended to allow mail to be accepted by whimsy-vmn.a.o if it is sent to @whimsy.a.o.
I assume it is OK for multiple hosts to include the same mydestination entry.
i.e. it won't cause problems if whimsy-vm5 is set up with the same setting.
=> INFRA-18405 - accept mail sent to whimsy.a.o

modules/jira_slack_bridge/files/slackbridge.yaml
Enabling slack jira bridge for Cassandra
=> Enabling slack jira bridge for Cassandra

modules/jira_slack_bridge/templates/jira-slack-bridge.py.erb
Log reconnections on the server, but this is unnecessary noise on a channel. Please, remove.
=> Remove unnecessary "notification enabled" notification

modules/subversion_server/files/authorization/pit-authorization-template
As per the discussions on private@infra and the relevate PMC lists, please update the PMC private area permissions:
Accumulo: https://lists.apache.org/thread.html/1733bbaa75a90626c7ac696e66e00b402c8b3cda4cfb13a8512d4e97@%3Cprivate.infra.apache.org%3E
APR: https://lists.apache.org/thread.html/5f78735d3a6d53af319d60012fcbef87483d581d0546823544cc7520@%3Cprivate.infra.apache.org%3E
Cocoon: https://lists.apache.org/thread.html/f9d018a481fecc8ece22dc1fc89480085c69b05dfc73e41939664b4e@%3Cprivate.infra.apache.org%3E
Jackrabbit: https://lists.apache.org/thread.html/91238d34be631604b4b039e8d2bcb22fcaf5775a77202aca82140232@%3Cprivate.infra.apache.org%3E
MyFaces: https://lists.apache.org/thread.html/8c714da424e494059f2b9538d423e9673582daed3975ce00b08783b8@%3Cprivate.infra.apache.org%3E
Tapestry: …
=> fix permissions for /pmc private areas

modules/subversion_server/files/authorization/pit-authorization-template
This restricts access to the newly created svn area for Ant to its PMC members.
=> restrict access to Ant PMC private svn

modules/buildbot_asf/files/projects/jmeter/create-jmeter-nightlies-index.sh
As can be seen at https://ci.apache.org/projects/jmeter/nightlies/r1409-c780783e832579ae6ec5717f39741d2f8e8b8768/ the filenames in my original script were missing an `r` before the git revision.
Relates to https://issues.apache.org/jira/browse/INFRA-18651
=> Add missing r before real revision to the filename of the nightlies

modules/customfact/lib/facter/customfact.rb
Ruby doesn't need escapes on the dots. Narrow the | operator. Switch from \d to [0-9] like the others.
=> correct an IP matcher regex

modules/svnqavm_pvm_asf/manifests/init.pp
Remove no-longer-supported release branches from the backport checker.
=> Remove no-longer-supported release branches

modules/svnqavm_pvm_asf/manifests/init.pp
Make the 'upcoming changes' generator look at a 'latest' symlink instead of hard-coding the branch name in here.
=> Make 'upcoming changes' look at 'latest' branch

modules/svnqavm_pvm_asf/manifests/init.pp
Now that svn-qavm3 on Ubuntu 14.04 is being migrated to svn-qavm on Ubuntu 18.04, it has a recent enough build of svn by default.
For https://issues.apache.org/jira/browse/INFRA-18508
=> Remove reference to a custom local svn build

modules/mboxer/manifests/init.pp
This is needed to allow mbox to archive the pmc-chairs alias
=> Alias for pmc-chairs

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
This publishes the content of `asf-git` branch in the `camel-website` gitbox repository to camel.apache.org/ (it used to publish to camel.apache.org/staging/) and disables the publish from SVN.
=> INFRA-18906: publish camel-website to root

data/nodes/bb-slave2.apache.org.yaml
Ruby 2.6.3 (latest stable version) installed on bb-slave2 with Ruby
2.3.1 (currently installed) set as the default
=> Use RVM to install Ruby 2.6.3

modules/gitwcsub/files/config/gitwcsub.cfg
Our website deploys from asf-site have stopped working likely on account of this.
See
* https://issues.apache.org/jira/browse/INFRA-18987
* https://issues.apache.org/jira/browse/INFRA-18914
=> Revert gitwcsub tracking branch for arrow.apache.org to asf-site

modules/svnqavm_pvm_asf/manifests/init.pp
as part of switching from svn-qavm3 to new svn-qavm. (Wayita is not transferred to svn-qavm yet.)
=> [INFRA-18508] Comment out all but wayita

modules/build_slaves/manifests/jenkins.pp
this script preinstalled on the y nodes emits a useless cron error every
hour and does nothing of note since unattended upgrades are alredy
enabled.
=> remove a useless script from y nodes

data/nodes/wilderness.apache.org.yaml
removing host entry for svn cause it's no longer in the same datacenter
=> removing host entry for svn cause it's no longer in the same datacenter

modules/webstats/files/webstats.py
Webstats.py should not scan committees that are not PMCs
Should also use the site attribute rather than mail_list which may not agree
=> Webstats.py fixes

modules/gitbox/files/asfgit/asfyaml.py
_**Note:** If there is a specific process in submitting a PR or feature request to INFRA in regards to this area, I am sorry ahead of time as I am not fully aware and would like to also learn the proper process. I had only read the contents from the Workflow link in README _
Support GitHub default feature settings.
It would be nice to be able to enable and disable the primary GitHub features with out needing to submit an INFRA ticket.
* Wikis
* Restrict editing to collaborators only
* This is a wiki related option.
* Issues
* Sponsorships
* Projects
This PR only focuses on providing support for the follow features:
* Wikis (`has_wiki`)
* Issues (`has_issues`)
* Projects (`has_projects`)
The parameter `name` are documented in https://developer.github.com/v3/repos/#edit
Example `.asf.yaml` …
=> feat: support GH feature settings in .asf.yaml

modules/ldapserver/templates/slapd.conf.erb
genmeta-rw should be able to re-create the ou=meta for project owner data.
=> Added the ACL for INFRA-19237

data/nodes/jenkins02.apache.org.yaml
redirect any Sonar analysis requests to documentation on how to use the replacement service.
=> redirect any Sonar analysis requests to documentation on how to use the replacement service.

modules/gitbox/files/asfgit/git_multimail.py
Clarify how change_type is derived, and allow for an unknown state (instead of throwing a KeyError)
=> clarify change_type

data/nodes/whimsy-vm4.apache.org.yaml
Makes a big difference in local testing ...
=> Ignore subgroups to speed up searching

modules/gitbox/files/cgi-bin/issues.cgi
See https://issues.apache.org/jira/projects/INFRA/issues/INFRA-19263
Rough attempt at implementing threading support for PR notifications, so that all email sent by the script for the same project and same issue/PR id will be grouped in the same email thread by mail clients, as per RFC2822 - https://tools.ietf.org/html/rfc2822.html#section-3.6.4
For new issues/PRs only, the `Message-ID` header of the email is set as `<issue.$ISSUEID.$PROJECTNAME.gitbox@gitbox.apache.org>`, for all other emails the message id is auto generated as before. For followup issues/PRs, such as comments, the `In-Reply-To` and `References` headers are set to that exact stable id.
For obvious reasons the changes are not tested, so this is an input to INFRA which may need some testing and adjustment before ready.
=> INFRA-19263: Threading of GitBox email messages

modules/gitbox/files/asfgit/asfyaml.py, modules/gitbox/files/cgi-bin/relay.cgi
This will allow projects to define GitHub users who should be allowed to push PRs to Jenkins via .asf.yaml.
Example .asf.yaml entry:
~~~
jenkins:
ghprb_whitelist:
- humbedooh
- janedoe
- githubmonkey
~~~
=> Allow projects to define whitelists for GHPRB

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
MINA [wants to migrate](https://lists.apache.org/thread.html/ra9014b092f25d3b4ad31d4251862c35c31d0a7ee0486ea3c9db59b0d%40%3Cdev.mina.apache.org%3E) from the Apache CMS and use git for serving its website.
[As discussed on slack](https://the-asf.slack.com/archives/CBX4TSBQ8/p1582565890030900) a follow-up PR will probably be created as well soon but this is just to get the first pieces in place and start using git.
Do I need to do something to get MINA deactivated from the [CMS](https://cms.apache.org/)?
=> Migrate MINA to gitpubsub

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
The Jena [community voted](https://lists.apache.org/thread.html/ra90da10830d6575b75f2f43f08e2886e0fff898e6391092bd86dc3ae%40%3Cdev.jena.apache.org%3E) to migrate away from the Apache CMS and use git for serving its website.
After this `cms.a.o/jena` needs to be removed and the cms.conf needs to be edited.
=> Migrated Jena from svnpubsub to gitpubsub

modules/mboxer/files/tools/archive.py
This would notify pypubsub whenever a public (not private or restricted lists) hit our mail servers.
Intended use for now is for an overall ASF activity visualizer, and will only notify about standard open channels such as users@, dev@ etc.
=> Notify pypubsub when public emails hit

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
After [voting](https://lists.apache.org/thread.html/r84c367fb0942ae66b2d693e43e1f38f446fd726257325953d2fede05%40%3Cdev.community.apache.org%3E) this moves community.a.o from svnpubsub to gitpubsub.
=> Migrated community.a.o from svnpubsub to gitpubsub

data/nodes/netbeans-vm.apache.org.yaml
Please review and merge my change which sets correct logfiles for netbeans-vm-ssl vhost on netbeans-vm.
=> netbeans-vm.apache.org: Setting correct access and error log files of httpd

modules/customfact/lib/facter/customfact.rb
The ipaddr module is used anyway in the customfact module,
so use it instead of brittle regex to check whether an
ip address is contained inside some network.
=> Use IPAddr module instead of regex for ip calculations

data/nodes/wicket-vm.apache.org.yaml, modules/wicket_pvm_asf/manifests/init.pp
Hi,
as discussed on our [mailing list ](http://mail-archives.apache.org/mod_mbox/wicket-dev/202001.mbox/%3CCAB63Y-d8kLUobxdJZ-qh2TCfT2VpD%2BEh7RUoOwd2Ec%2BQN0MJfg%40mail.gmail.com%3E) we would like to have an examples site also for the upcoming version 9 of Wicket. We also decided to serve our examples sites over SSL by default. I've changed the 2 config file accordingly. Please note that I've chosen port 8089 for the new 9.x site. I hope it's ok on your side.
Thank you.
=> Create 9.x examples site and force SSL

data/roles/tlpserver.yaml
- Previous redirect was just ending up in a directory listing - better redirect to an actual page with relevant information
=> [UIMA-6237] Remove old documentation from website

modules/svnwcsub/files/svnwcsub.conf
On hold till https://github.com/apache/vcl-site/pull/2 & https://github.com/apache/vcl-site/pull/3 are merged.
=> Removed VCL site from svnpubsub

data/common.yaml
it is a dynamic system filesystem and causes bpc errors
=> add /var/lib/lxcfs to bpc excludes

data/common.yaml
this works around a backuppc bug where the ping command doesn't seem to
work with $pingPath as defined, so we hardcode /bin/ping.
=> force a client ping command to /bin/ping

modules/gitbox/files/asfgit/asfyaml.py, modules/gitbox/files/asfgit/cfg.py
This will allow notifications to be set using the default branch where that branch differs from 'master' or 'trunk'.
=> default branch detection for .asf.yaml operations

modules/mysql_asf/templates/dbsave_mysql.sh.erb
change this to increase max packet size, and add appropriate flags for
dumping InnoDB tables without a full DB lock. previous dumps MAY have
been inconsistent without this.
=> actually use DUMPOPTS parameter

modules/gitbox/files/asfgit/git.py, modules/gitbox/files/conf/gitconfig
This is for branch protection rules, allowing us to move away from 'master' and towards just pointing at the default branch, for those cases where the default needs protection but isn't called master.
=> Allow for magic variable $default, pointing to default branch of any repo

modules/projects_pvm_asf/manifests/init.pp
The cronjobs are enabled on projects-vm3 in https://github.com/apache/infrastructure-p6/commit/d2b38868e81e397c31994ba840e8056c2c2f8343 (the machine is deployed from the `env/` branch because of me lacking permissions to deploy otherwise)
/cc @Humbedooh
=> Disable cronjobs on projects-vm2

environments/windows/modules/jenkins_node_windows/files/toolchains.xml, environments/windows/modules/jenkins_node_windows/manifests/init.pp
This is a follow-up on https://issues.apache.org/jira/browse/INFRA-20938
* Fixes jdkHome for Java 1.9: It is `F:\\jenkins\\tools\\java\\latest9\\` and not `F:\\jenkins\\tools\\java\\latest1.9\\`
* Removes toolchain config for jdk16, since jdk16 doesn't seem to be available for windows nodes? At least, I couldn't find it in https://github.com/apache/infrastructure-puppet/blob/1d17bdd455b8f747d86e9c2ae6979284d763a752/environments/windows/modules/jenkins_node_windows/manifests/params.pp#L13
=> Fix jdkHome for Java 1.9, remove jdk16 - INFRA-20938

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, environments/windows/modules/jenkins_node_windows/manifests/init.pp, environments/windows/modules/jenkins_node_windows/manifests/params.pp, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
Add openjdk16-ea+24 to all buildbot and jenkins nodes still using devops/puppet3
=> Add openjdk16-ea+24 to all buildbot and jenkins nodes still using devops/puppet3

modules/svnwcsub/files/svnwcsub.conf
The Directory TLP uses the .asf.yaml now for publishing their website (from the directory-site repo).
=> Directory moved from the CMS to git with usage of the .asf.yaml

modules/gitbox/files/asfgit/git_multimail.py
Although email headers contain the information, many people don't know how to view them.
=> Add unsubscribe footer to emails

modules/gitbox/files/asfgit/git_multimail.py
This was fixed in the source in 6d19ac2:
The commit says it is unlikely to affect behaviour,
but I wonder if this could relate to
INFRA-21595 - sendmail error during push to gitbox
=> Fix typo in class name

modules/gitbox/files/asfgit/cfg.py
If a config item value contains '=', the code crashes with a message such as
ValueError: dictionary update sequence element #17 has length 3; 2 is required
The fix is to only split once.
=> config item values may contain =

modules/gitbox/files/hooks/post-receive.d/02-send-emails.py
The environment parameter is expected to contain a get_logger() attribute.
This is not the case for os.environ.
I think this is what caused the following error message:
remote: Error: _Environ instance has no attribute 'get_logger' 
as reported in:
INFRA-21595 - sendmail error during push to gitbox
=> Fix environment parameter to SendMailer class

modules/gitbox/files/bin/repo-archive.py
repo-archive.py is a mutation of attic-repos.py with argparse,
capable of supporting both the archival of a single repo, as
well as an entire project.
usage: repo-archive.py [-h] (-R/--retire-project | -A/--archive-repo) [-n/--name NAME] [-d/--debug]
=> repo-archive.py

modules/gitbox/files/asfgit/asfyaml.py
autobuild will automatically site-build any pelican branch matching the autobuild target glob, for example site/*. The output will be in $branch-staging, e.g. site/foo-staging.
autostage will automatically stage any matching branch ending in '-staging'. For instance, site/* will stage site/foo-staging as $project-foo.staged.a.o, whereas it would not stage site/foo (as that is considered a source branch).
=> add autobuild to pelican, add autostage to staging

modules/gitbox/files/asfgit/asfyaml.py
This allows up to 20 people to be listed as collaborators with triage role assigned for a repository on github.
=> Add triage collaborator feature

modules/gitbox/files/asfgit/asfyaml.py
Note: the RE check is likely to be superfluous if done last, as errors should be caught by the check against valid_lists.
If the RE check does fail, it is possible that the RE is too strict, otherwise why would the list be in valid_lists?
=> Do the cheapest checks first
