data/nodes/erebus-ssl.apache.org.yaml
Puppet manifest for erebus-ssl proxy
=> Add erebus-ssl manifest

modules/blogs_asf/manifests/init.pp
=> user variables

modules/rsync_mirror/files/rsync_hang.pl, modules/rsync_mirror/manifests/init.pp
In reference to INFRA-9470, I have done some clean up on the rsync mirror modules.
I have also added Henk's script (with some minor output tweaking) to be run as a cron to clean up stale rsync connections.
=> Tune up rsync mirror module

data/nodes/forrest-vm.apache.org.yaml, modules/forrest_pvm_asf/manifests/init.pp
* add bsd-mailx for sending mail from role account
* forrest role account
* ownership of apache docroot
=> Update forrest-vm puppet configuration

data/nodes/proxy4-us-west.apache.org.yaml
Initial vhost config for tapestry-vm
=> initial addition of tapestry-vm proxy vhost

Puppetfile, data/nodes/whimsy-vm2.apache.org.yaml, modules/whimsy_server/manifests/init.pp
Note: puppetlabs/passenger didn't work for me, at least not with a recent version of passenger; I noted that there is a fix on master that purports to make it work, but I still couldn't get it to work.  Looking around, I found an alternative with rvm, which as an added bonus gives me a newer version of Ruby.
=> get passenger up and running

data/nodes/whimsy-vm2.apache.org.yaml, modules/vhosts_whimsy/README.md, modules/vhosts_whimsy/lib/puppet/parser/functions/preprocess_modules.rb, modules/vhosts_whimsy/lib/puppet/parser/functions/preprocess_vhosts.rb, modules/vhosts_whimsy/manifests/custom_config.pp, modules/vhosts_whimsy/manifests/modules.pp, modules/vhosts_whimsy/manifests/vhosts.pp
See README for list of features.
=> Create a vhost_whimsy module based on vhost_asf

data/nodes/whimsy-vm2.apache.org.yaml, modules/vhosts_whimsy/README.md, modules/vhosts_whimsy/lib/puppet/parser/functions/preprocess_vhosts.rb, modules/whimsy_server/manifests/init.pp
Mostly setting up directories for svn and mail data; add an apmail user; set up an svn update cron job.
Also deploys roster and secmail passenger applications, corrects LDAP for secretary, installs imagemagic and pdftk tools used by secmail.
=> Framework for svn and mail data sources

modules/whimsy_server/manifests/init.pp
install nodejs; fix puppet lint errors
=> Whimsy nodejs

data/nodes/whimsy-vm2.apache.org.yaml, modules/vhosts_whimsy/lib/puppet/parser/functions/preprocess_vhosts.rb
* get AuthLDAP working
* set HTTPS correctly
* disable Spelling and MutltiViews for Passenger applications
* general cleanup
=> http configuration cleanup

data/nodes/whimsy-vm2.apache.org.yaml, modules/whimsy_server/manifests/init.pp
Also fix public_member cronjob
=> Add the board minutes tool as a cronjob

data/nodes/whimsy-vm2.apache.org.yaml, modules/whimsy_server/manifests/cronjobs.pp
=> Move cron jobs from yaml to module

modules/subversion_server/files/authorization/asf-authorization-template
See http://incubator.apache.org/projects/taverna.html
> Chris Mattman ➝ Dan Debrunner
=> Modify taverna membership after mentor swap

modules/subversion_server/files/authorization/pit-authorization-template
the general request (https://issues.apache.org/jira/browse/INFRA-11742) is
addressed by https://svn.apache.org/repos/private
=> add a pmc/trademarks to resolve the specific issue

modules/subversion_server/files/authorization/asf-authorization-template
Let me know if I should point to a different branch.
=> Added Phil Ottlinger to tamaya.

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/asf-mailer.conf
See also: https://meta.wikimedia.org/wiki/Cunningham's_Law
=> attempt to fix INFRA-12046

modules/subversion_server/files/authorization/asf-authorization-template
ranger += bganesan,coheigea,gautam,madhan,vel
=> Add new committers to the ranger auth group.

data/nodes/whimsy-vm3.apache.org.yaml, modules/whimsy_server/manifests/cronjobs.pp, modules/whimsy_server/manifests/init.pp
For cron jobs, CGI scripts, and Rack applications.
=> Update Ruby to 2.3.1

modules/subversion_server/files/authorization/asf-authorization-template
Hi INFRA, a trivial update to asf-authorization-template here to add new SensSoft project and also correct an invalid addition for Joshua (this was previously my fault for committing directly)
=> Add senssoft to asf-authorization-template and correct joshua definition

modules/subversion_server/files/authorization/asf-authorization-template
Add Michael Wu (mw) to asf-authorization-template for Apache Eagle incubating
=> Add committer Michael Wu (mw) to Eagle svn access.

modules/subversion_server/files/authorization/asf-authorization-template
=> Add eyal to DataFu podling by jghoman

modules/whimsy_server/files/board-agenda-websocket.conf, modules/whimsy_server/manifests/init.pp
tested using infrastructure-playpen and vagrant
=> start whimsy board agenda websocket service

modules/subversion_server/files/authorization/asf-authorization-template
This adds the rest of the committers as well as a new committer (caleb) to the rya group.
=> Update the rest of the Rya podling members

data/nodes/vmgump-vm3.apache.org.yaml, modules/gump_server/files/.gitconfig, modules/gump_server/files/localenv.sh, modules/gump_server/files/post-run.sh, modules/gump_server/files/testbed.xml, modules/gump_server/manifests/cronjobs.pp, modules/gump_server/manifests/init.pp
This is the bare infrastructure I'll need in order to test whether Gump works at all, it is likely not the last pull request before we can decommission vmgump.
=> INFRA-12291 first steps towards puppetizing vmgump

modules/subversion_server/files/authorization/asf-authorization-template
=> Add id 'maanadev' to podling Taverna svn

modules/subversion_server/files/authorization/asf-mailer.conf
This time with the right path *sigh*
=> second attempt to get president commit messages to operations@

data/nodes/bb-slave5.apache.org.yaml
Add missing packages needed to build with the same options as a release build.
=> Add missing packages

modules/subversion_server/files/authorization/asf-authorization-template
=> Add 'rajanmaurya154' and 'sagar' to podling Taverna

data/nodes/vmgump-vm3.apache.org.yaml, modules/gump_server/files/localenv.sh, modules/gump_server/manifests/cronjobs.pp, modules/gump_server/manifests/init.pp
This contains several steps necessary to replace vmgump. If all works the way I expect it to the only issue remaining is that vmgump-vm3 must be able to send emails -> #140
=> INFRA-12291 Vmgump3 setup

modules/gump_server/manifests/init.pp, modules/gump_server/manifests/opt_package.pp
this also contains a small dependency fix for `opt_package` that I found while doing a clean install. I can split it into a fresh PR if you prefer.
=> Upgrade mono on vmgump to a new version

modules/subversion_server/files/authorization/asf-authorization-template
Remove Henry Saputra (hsaputra) from Tephra committership due to resign from mentorhsip.
=> Remove Henry Saputra (hsaputra) from Tephra committership.

data/nodes/mergebot-vm.apache.org.yaml
=> Add tmux to mergebot-vm

modules/subversion_server/files/authorization/asf-authorization-template
Adding entry for Apache Griffin incubating:
https://wiki.apache.org/incubator/GriffinProposal
=> [INFRA-13100] Add access control for Apache Griffin incubating.

data/nodes/ponymail-vm.apache.org.yaml
Need to enable Lua as CGI; please merge
=> Add updates from configs/ponymail_httpd.conf

modules/subversion_server/files/authorization/asf-authorization-template
Adding access to SVN and git for hsaputra as new mentor for SystemML incubating.
=> Update access for sysmetml for hsaputra as mentor.

modules/subversion_server/files/authorization/asf-authorization-template
This issue relates to https://issues.apache.org/jira/browse/INFRA-13146 it simply removes an incorrect entry. We will deal with the other issues on our mailing list.
=> Remove incorrect sensoft entry from asf-auth

data/nodes/syncope-vm2.apache.org.yaml
removing
- ProxyHTMLExtended      On
- ProxyHTMLURLMap
from the various httpd location configs
=> INFRA-11960 - Removing httpd config elements

modules/subversion_server/files/authorization/asf-authorization-template
Please review the changes to asf-authorization-template to add new podling ratis.
=> Add ratis to auth template

modules/buildbot_asf/files/projects/create-ofbiz-archives-index.sh, modules/buildbot_asf/files/projects/create-ofbiz-snapshots-index.sh
This PR to update the  OFBiz snapshots page
=> INFRA-13451 - updates OFBiz snapshots page

modules/subversion_server/files/authorization/asf-authorization-template
Add access for Griffin for initial committers
https://wiki.apache.org/incubator/GriffinProposal
=> Add access for Griffin initial committers.

modules/gitbox/files/asfgit/hooks/gitpubsub.py
=> [INFRA-13649] Was supposed to send push events for *every* push

data/nodes/whimsy-vm3.apache.org.yaml
NOTE: I'm presuming this is the correct way to add local ErrorDocument for whimsy host itself - review appreciated when time available.
=> Proposed change to use new custom error pages.

modules/git_mirror_asf/files/bin/update-index.sh
Mention Gitbox, expand the writable git details a little bit, and update infra list to direct queries to
=> Git homepage update

modules/ldapserver/templates/slapd.conf.erb
Hold on merging this until I say so.  I specifically want to get the following, in order: (1) the OK of David and/or Greg, (2) to pass it by the board, and then (3) pass it by the membership.
Discussion thread:
https://lists.apache.org/thread.html/9f79cce1ab235cd916128988a67303941d22ae9f42e2ac3eba1f7483@%3Cprivate.infra.apache.org%3E
LDAP documentation:
http://www.openldap.org/doc/admin24/access-control.html#Group%20ACLs%20without%20DN%20syntax
=> allow ASF members to update group ACLs

modules/whimsy_server/files/whimsy-pubsub.conf, modules/whimsy_server/files/whimsy-pubsub.service, modules/whimsy_server/manifests/init.pp
fetches the changes and deploys them.
=> Whimsy pubsub support: watches for updates to the whimsy repository,

modules/build_slaves/templates/git-credentials.erb
I'm pretty sure we'll need credentials for gitbox listed here as well.
=> INFRA-14379

modules/subversion_server/files/authorization/pit-authorization-template
testing. use a PR to merge a branch into deployment, via the GitHub web UI
=> remove selfserve auth section

data/nodes/tlp-eu-new.yaml
As subject says, this adds yaml for the new VM. It won't go live yet, needs to sync up with svn for quite a while. This is slated to replace tlp-eu-mid if all goes well.
=> add yaml for tlp-eu-new on garl

modules/ssl/manifests/name/archive_apachecon_com.pp
=> lrn2namefiles

modules/subversion_server/files/authorization/asf-mailer.conf
=> fix path for email

modules/jenkins_asf/templates/setenv.sh.erb
=> enable cacerts

data/colo/phoenixnap-private.yaml
=> remove the broken private binding for pnap ldap and add the lw one as

modules/subversion_server/files/authorization/generate-dist-authorization
@clambertus this completes what we were working on last night
=> add projects to distribution auth

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-14663 gobblin gitpubsub

data/nodes/jenkins-cassandra10.apache.org.yaml, data/nodes/jenkins-cassandra11.apache.org.yaml, data/nodes/jenkins-cassandra12.apache.org.yaml, data/nodes/jenkins-cassandra13.apache.org.yaml, data/nodes/jenkins-cassandra14.apache.org.yaml, data/nodes/jenkins-cassandra15.apache.org.yaml, data/nodes/jenkins-cassandra8.apache.org.yaml, data/nodes/jenkins-cassandra9.apache.org.yaml
add jenkins-cassandra{8..15}.apache.org to puppet re: https://issues.apache.org/jira/browse/INFRA-14153
=> INFRA-14153 add new cassandra nodes

data/common.yaml, data/nodes/bb-slave6.apache.org.yaml, data/nodes/jenkins-cassandra1.apache.org.yaml, data/nodes/jenkins-cassandra10.apache.org.yaml, data/nodes/jenkins-cassandra11.apache.org.yaml, data/nodes/jenkins-cassandra12.apache.org.yaml, data/nodes/jenkins-cassandra13.apache.org.yaml, data/nodes/jenkins-cassandra14.apache.org.yaml, data/nodes/jenkins-cassandra15.apache.org.yaml, data/nodes/jenkins-cassandra2.apache.org.yaml, data/nodes/jenkins-cassandra3.apache.org.yaml, data/nodes/jenkins-cassandra4.apache.org.yaml, data/nodes/jenkins-cassandra5.apache.org.yaml, data/nodes/jenkins-cassandra6.apache.org.yaml, data/nodes/jenkins-cassandra7.apache.org.yaml, data/nodes/jenkins-cassandra8.apache.org.yaml, data/nodes/jenkins-cassandra9.apache.org.yaml, data/nodes/ponymail-vm.apache.org.yaml, data/nodes/qnode1.quenda.co.yaml, data/nodes/qnode2.quenda.co.yaml, data/nodes/qnode3.quenda.co.yaml, data/nodes/qnode4.quenda.co.yaml, data/nodes/qnode5.quenda.co.yaml, data/nodes/sa-vm1.apache.org.yaml, data/nodes/sensoft-vm.apache.org.yaml, data/nodes/tobago-vm.apache.org.yaml, data/nodes/tools-vm.apache.org.yaml
replacing snappy5 with ldap1-lw-us for ldap lookups
=> sed s/snappy5/ldap1-lw-us/

data/ubuntu/1404.yaml, data/ubuntu/1604.yaml, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
=> Add jdk1.8.0_144 unlimited security version

modules/cwiki_asf/manifests/init.pp
=> Allow Confluence access to create dirs/files inside conf/Standalone

data/nodes/whimsy-vm3.apache.org.yaml, data/nodes/whimsy-vm4.apache.org.yaml
=> Use relative+permanent redirects

modules/vhosts_whimsy/README.md, modules/vhosts_whimsy/lib/puppet/parser/functions/preprocess_vhosts.rb
Tested with https://github.com/apache/whimsy/blob/master/tools/vhosttest.rb
=> correct indentation

modules/git_self_serve/templates/ss.lua.erb
Use HTTP request (for now?) tro fetch podlings, filter them out of LDAP.
Also adjust LDAP to new structure and closest server.
=> fix LDAP lookups for reporeq

data/nodes/ponymail-vm.apache.org.yaml
=> Try to fix missing data

modules/buildbot_slave/manifests/init.pp
Already declared in the ubuntu 14|16 yamls
=> remove dupe declaration of datadog class in buildbot.

data/nodes/bb-slave1.apache.org.yaml, data/nodes/bb-slave2.apache.org.yaml, data/nodes/bb-slave3.apache.org.yaml, data/nodes/bb-slave4.apache.org.yaml, data/nodes/bb-slave5.apache.org.yaml, data/nodes/lares.apache.org.yaml, data/nodes/orcus.apache.org.yaml, data/nodes/silvanus.apache.org.yaml
- moved it into buildbot base now via 14.04.yaml
=> remove yaml declarations of openjd7-jdk 

data/nodes/home.apache.org.yaml
home.a.o needs to use ldap_projects.json
=> Fetch projects.json

modules/gitbox/files/bin/gitbox-bulk-clone.py
beware of repos with no description, tweak grammar
=> beware of repos with no description, tweak grammar

modules/gitbox/files/cgi-bin/sync-repo.cgi
=> switch to pruning by default, fix typo

modules/gitbox/files/bin/gitbox-bulk-clone.py
remove stale webhooks after cloning
=> remove stale webhooks after cloning

modules/gitbox/files/bin/gitbox-bulk-clone.py
=> fix calls etc

data/nodes/whimsy-vm4.apache.org.yaml
Related: https://issues.apache.org/jira/browse/INFRA-11080
=> relay travis emails so that they can be moderated

modules/subversion_server/files/authorization/pit-authorization-template
=> add dir for beam pmc

data/nodes/tools-vm.apache.org.yaml
prep vhost for new selfserve portal
=> prep vhost for new selfserve portal

modules/selfserve/files/selfserve/templates/base.html, modules/selfserve/files/selfserve/templates/changedetails.html, modules/selfserve/files/selfserve/templates/index.html, modules/selfserve/files/selfserve/templates/layout.html
tweak id.a.o design to conform to new self serve portal.
=> tweak id.a.o design to conform to new self serve portal.

modules/selfserve_portal/manifests/init.pp, modules/selfserve_portal/templates/jira-get-category.sh.erb
Add an initial script to populate a json file with available Jira Categories, so that the form can use it as a drop down menu
=> Add an initial script to populate a json file with available Jira Categories, so that the form can use it as a drop down menu

modules/selfserve/files/selfserve/templates/base.html, modules/selfserve/files/selfserve/templates/layout.html, modules/selfserve_portal/files/site/css/default.css
=> tweak css for id.a.o

modules/selfserve_portal/files/site/cgi-bin/createml.cgi
add in some suggestions from sebb
=> add in some suggestions from sebb

data/nodes/tools-vm.apache.org.yaml
allow secretary access as well
=> allow secretary access as well

modules/selfserve_portal/files/site/cgi-bin/createml.cgi, modules/selfserve_portal/files/site/cgi-bin/jirauser.cgi, modules/selfserve_portal/files/site/cgi-bin/sscommon.py, modules/selfserve_portal/files/site/index.html, modules/selfserve_portal/files/site/js/mailform.json
allow foo, foo-bar, but not -foo-bar- etc.
=> allow foo, foo-bar, but not -foo-bar- etc.

modules/selfserve_portal/files/site/mail.html
=> forgot body tweak here

data/nodes/mbox-vm.apache.org.yaml, modules/mboxer/files/tools/archive.py, modules/mboxer/files/tools/settings.yml, modules/mboxer/manifests/init.pp
=> initial stab at mbox-vm

modules/mboxer/manifests/init.pp
=> we need this package

modules/mboxer/manifests/init.pp
=> fix missing brackets

modules/mboxer/manifests/init.pp
=> set owner to nobody

modules/mboxer/files/tools/archive.py
=> updates to archive.py

data/nodes/mbox-vm.apache.org.yaml
allow access to members, disallow others
=> allow access to members, disallow others

modules/mboxer/files/tools/archive.py
change permissions as we make new dirs
=> change permissions as we make new dirs

modules/mboxer/files/tools/archive.py
=> comma fixes

modules/mboxer/files/tools/archive.py, modules/mboxer/files/tools/settings.yml, modules/mboxer/manifests/init.pp
=> set up restricted arch

modules/mboxer/files/tools/archive.py
=> fix paths and perms

modules/mboxer/files/tools/archive.py
=> only accept kosher recipients

modules/mboxer/files/tools/archive.py
=> first char should be a-z0-9

modules/mboxer/files/tools/archive.py
=> forgot to import errno

modules/mboxer/files/tools/archive.py
in py3, we can set a flag to run makedirs if path exists
=> in py3, we can set a flag to run makedirs if path exists

data/nodes/mbox-vm.apache.org.yaml
=> yeah we don't use this...ahem

modules/mboxer/files/tools/archive.py
- Need to allow for EACCESS in flock
- From_ line is in UTC but must not include the TZ id
- Only 1 trailing line needed in mboxes
- mbox files use EOL=LF, not CRLF
- Escape >*From as well
- Don't add spurious LF if bad input message starts with From
- Need to lock the dumpfile too
- Properly match apache.org
- Use UTC for determining current month (locale-independence)
=> Fix various bugs in archive.py

data/nodes/mbox-vm.apache.org.yaml
=> postfix requires a cert

modules/mboxer/files/tools/archive.py
if we get an email we can't find a target for, we should bork
=> if we get an email we can't find a target for, we should bork

data/nodes/tools-vm.apache.org.yaml
=> open up SSP to chairs

modules/selfserve_portal/files/site/cgi-bin/sscommon.py
=> add message-id to headers

modules/selfserve_portal/files/site/cgi-bin/createml.cgi, modules/selfserve_portal/files/site/mail.html
shortcut for making three lists in one go + force privacy.
=> shortcut for making three lists in one go + force privacy.

modules/selfserve_portal/files/site/cgi-bin/createconfluence.cgi, modules/selfserve_portal/files/site/cgi-bin/createjira.cgi, modules/selfserve_portal/files/site/cgi-bin/createml.cgi, modules/selfserve_portal/files/site/cgi-bin/sscommon.py
email was shadowed, rendering email.utils uncallable. fix that.
=> email was shadowed, rendering email.utils uncallable. fix that.

modules/selfserve_portal/files/site/mail.html
=> emphasis etc

modules/subversion_server/manifests/init.pp
=> downsize viewvc to 8 workers

modules/subversion_server/files/authorization/asf-authorization-template
INFRA-14977: make directory/shared read-only
=> INFRA-14977: make directory/shared read-only

modules/selfserve_portal/files/site/cgi-bin/createml.cgi
One possible solution to protecting against concurrent writes from different sessions
=> Must lock file against concurrent write

modules/mboxer/files/tools/archive.py
- localise variables
- use meaningful names
- don't reuse names unnecessarily
- use os.path.join to create paths; build up in stages
- comment fixes
- use LF not CRLF in writes to stderr
- include list-post in stderr
=> Fixes to archiver

modules/gitwcsub/files/config/gitwcsub.cfg
updated accumulo-website to gitbox
=> updated accumulo-website to gitbox

modules/mboxer/files/tools/archive.py
Call dumpbad for FQDN errors too
=> Archive fix

modules/selfserve_portal/files/site/js/mailform.json, modules/selfserve_portal/files/site/mail.html
let's ditch the private checkbox for now.
=> let's ditch the private checkbox for now.

modules/gitbox/files/cgi-bin/issues.cgi
=> add remote links to PRs

data/nodes/mbox-vm.apache.org.yaml
tighten permissions for inbound mail.
=> tighten permissions for inbound mail.

modules/gitbox/files/cgi-bin/issues.cgi
correct data format for PR links
=> correct data format for PR links

modules/subversion_server/files/authorization/asf-authorization-template
=> missing leading /

modules/selfserve_portal/files/site/cgi-bin/sscommon.py
INFRA-15014: Add Date: header to emails from SSP
=> INFRA-15014: Add Date: header to emails from SSP

data/nodes/community-vm.apache.org.yaml
initial stab at a new comdev VM on garl
=> initial stab at a new comdev VM on garl

data/nodes/community-vm.apache.org.yaml
add vhosts to make puppet happy.
=> add vhosts to make puppet happy.

data/nodes/community-vm.apache.org.yaml
gunicorn is installed by default, ditch it
=> gunicorn is installed by default, ditch it

modules/subversion_server/files/authorization/pit-authorization-template
This is needed for INFRA-14792.
=> Allow hermes apmail login to check SVN sync status

data/nodes/community-vm.apache.org.yaml
proxy community-vm.a.o to gunicorn backend
=> proxy community-vm.a.o to gunicorn backend

data/nodes/community-vm.apache.org.yaml
wrong port, we don't want tomcat
=> wrong port, we don't want tomcat

data/nodes/es-cluster-eu-01.apache.org.yaml
require root or logging ldap group for kibana
=> require root or logging ldap group for kibana

modules/gitwcsub/files/config/gitwcsub.cfg
=> change location of repo

modules/gitbox/files/matt/site/index.html
elaborate on invites from github
=> elaborate on invites from github

modules/subversion_server/files/authorization/asf-authorization-template
mark myfaces/tobago as read-only.
=> mark myfaces/tobago as read-only.

data/nodes/jenkins-win-1.apache.org.yaml, environments/windows/modules/wintest/manifests/init.pp
Getting the base of something in for Windows testing.
=> Getting the base of something in for Windows testing.

data/nodes/jenkins-win-1.apache.org.yaml
Adding windows environment to test yaml
=> Adding windows environment to test yaml

environments/windows/modules/base/init.pp
Adding a blank base module to the windows env
=> Adding a blank base module to the windows env

environments/test/environment.conf
Testing the test environment to make sure ./modules is a thing that works
=> Testing the test environment to make sure ./modules is a thing that works

environments/test/environment.conf
=> Rolling back my changes

modules/gitbox/files/cgi-bin/issues.cgi
INFRA-12732 - Add a label on PR
=> INFRA-12732 - Add a label on PR

modules/subversion_server/files/authorization/pit-authorization-template
INFRA-15073: PMC Dir for Ignite
=> INFRA-15073: PMC Dir for Ignite

data/nodes/jenkins-win-1.apache.org.yaml, environments/windows/manifests/site.pp
trying to narrow the scope so puppet only pulls windows classes
=> trying to narrow the scope so puppet only pulls windows classes

modules/svngit2jira/files/config/svngit2jira.cfg
we're only interested in news from deployment.
=> we're only interested in news from deployment.

modules/subversion_server/files/authorization/pit-authorization-template
allow apmail to commit to apmail/bin/
=> allow apmail to commit to apmail/bin/

modules/subversion_server/files/authorization/pit-authorization-template
=> wrong path, opps

data/common.yaml, data/nodes/jenkins-win-1.apache.org.yaml
Moving class from windows specific yaml to common.yaml
=> Moving class from windows specific yaml to common.yaml

modules/subversion_server/files/authorization/asf-authorization-template
=> INFRA-15083 - grant temp access to HC branch

modules/subversion_server/files/authorization/asf-authorization-template
=> INFRA-14883 mark myfaces/trinidad as readonly

data/nodes/mbox-vm.apache.org.yaml
=> document our failure ;(

Puppetfile
=> Added tags to puppetfile

environments/windows/environment.conf
Pretty sure this is a : not a ;
=> Pretty sure this is a : not a ;

environments/windows/modules/datadog_agent/manifests/init.pp
Changing name of class being called for download_file
=> Changing name of class being called for download_file

Puppetfile
Renaming and grouping modules in Puppetfile
=> Renaming and grouping modules in Puppetfile

Puppetfile
=> Fixing tag in puppetfile

data/nodes/jenkins-win-1.apache.org.yaml
renaming the new jenkins windows box
=> renaming the new jenkins windows box

modules/gitbox/files/asfgit/git_multimail.py
nix reply-to fields from multimail.
=> nix reply-to fields from multimail.

modules/gitwcsub/files/config/gitwcsub.cfg
=> Add pubsub for royale

modules/mboxer/files/tools/archive.py
The code currently rejects apachecon.com and mod_ftp
=> Allow for apachecon.com and mod_ftp-dev

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-15152: Move site repo

modules/gitbox/files/asfgit/git_multimail.py, modules/gitbox/files/cgi-bin/sync-repo.cgi
if wiki diff (gollum event), then fetch wiki changes and run multimail on that
=> if wiki diff (gollum event), then fetch wiki changes and run multimail on that

modules/gitbox/files/asfgit/cfg.py, modules/gitbox/files/asfgit/git_multimail.py, modules/gitbox/files/cgi-bin/sync-repo.cgi
=> fix known bugs so far

modules/gitbox/files/asfgit/git_multimail.py, modules/gitbox/files/cgi-bin/sync-repo.cgi
=> clone as mirror and use fetch

data/nodes/tlp-eu-west.apache.org.yaml
=> add yaml for tlp-eu-west

data/nodes/svn01-us-west.apache.org.yaml
=> Adding kif to svn01

data/ubuntu/1404.yaml, data/ubuntu/1604.yaml
changing datadog log level to error from info
=> changing datadog log level to error from info

data/nodes/whimsy-vm4.apache.org.yaml
Allow access to bootstrapping files without authorization
=> prep for service workers

modules/gitbox/files/cgi-bin/sync-repo.cgi
actually add return code and text to output
=> actually add return code and text to output

modules/vhosts_whimsy/lib/puppet/parser/functions/preprocess_vhosts.rb
Part 1 of 2.
Whereas yesterday, I only tested with apache httpd; this is also tested against puppet.
After this change is applied, the puppet master needs to be restarted to refresh its cache of parser functions.
=> Provide a means for exceptions to authentication rules

data/nodes/jenkins-win2016-1.apache.org.yaml, environments/windows/environment.conf
Removing the jenkins_slave_module from yaml
=> Removing the jenkins_slave_module from yaml

environments/windows/environment.conf
Adding the future parser back into the windows environment
=> Adding the future parser back into the windows environment

data/nodes/jenkins-win2016-1.apache.org.yaml, modules/jenkins_slave_windows/manifests/init.pp
Adding the jenkins_slave_windows module back
=> Adding the jenkins_slave_windows module back

data/nodes/whimsy-vm4.apache.org.yaml
=> redirect http://whimsy.apache.org to https://whimsy.apache.org

modules/svngit2jira/files/config/svngit2jira.cfg
INFRA-15243: Add svngit2jira for Creadur
=> INFRA-15243: Add svngit2jira for Creadur

modules/mboxer/files/tools/archive.py
No point parsing the entire message since only some of the headers are used
=> Only parse headers

data/nodes/reviews-vm2.apache.org.yaml
add some comments on reviewboard fixes
=> add some comments on reviewboard fixes

modules/vhosts_whimsy/lib/puppet/parser/functions/preprocess_vhosts.rb
No functional changes included in this commit
=> Per convention, capitalize Apache http directive

data/nodes/lares.apache.org.yaml, modules/buildbot_slave/files/forrest.xml, modules/buildbot_slave/files/pdfbox.xml, modules/buildbot_slave/files/subversion.xml
Add rat report xml files to lareas node
=> Add rat report xml files to lareas node

modules/gitwcsub/files/config/gitwcsub.cfg
=> move netbeans to gitbox

modules/gitbox/files/cgi-bin/issues.cgi
=> pull in diffs on fork PRs

modules/gitbox/files/cgi-bin/issues.cgi, modules/gitbox/files/cgi-bin/template.ezt
=> use the ezt template, bleh

modules/loggy/files/loggy.py
Tell ES to ignore malformed entries by default
=> Tell ES to ignore malformed entries by default

modules/rootbin_asf/files/bin/www/rsyncd.conf, modules/rsync_mirror/manifests/init.pp
=> INFRA-14757 rm dist/zzz/perms

modules/gitbox/files/cgi-bin/issues.cgi
=> Add message-id to emails

modules/gitwcsub/files/config/gitwcsub.cfg
=> add kibble website to pubsub

data/nodes/rsync-eu.apache.org.yaml, modules/svnwcsub/files/svnwcsub.conf.dist
add base yaml and svnwcsub role for rsync-only box (rsync-eu.a.o)
=> add base yaml and svnwcsub role for rsync-only box (rsync-eu.a.o)

modules/gitwcsub/files/config/gitwcsub.cfg
=> move sling-site pubsub

modules/gitwcsub/files/config/gitwcsub.cfg
=> move airavata site

modules/gitbox/files/cgi-bin/issues.cgi
default to having JIRA mirroring enabled
=> default to having JIRA mirroring enabled

modules/svnwcsub/files/svnwcsub.conf
INFRA-15323: Set up staging dir for svn
=> INFRA-15323: Set up staging dir for svn

modules/mboxer/files/tools/archive.py
See https://issues.apache.org/jira/browse/INFRA-15245
=> INFRA-15245 trust List-Post

data/nodes/jenkins-win2016-1.apache.org.yaml, modules/jenkins_slave_windows/manifests/init.pp
Adding the jenkins windows module back with new JDK downloads.
=> Adding the jenkins windows module back with new JDK downloads.

data/common.yaml
Removing wintest from common.yaml
=> Removing wintest from common.yaml

data/common.yaml
commenting out the windows modules
=> commenting out the windows modules

data/nodes/jenkins-win2016-1.apache.org.yaml, environments/windows/modules/jenkins_slave_windows/manifests/init.pp
Adding the windows jenkins module back into prod
=> Adding the windows jenkins module back into prod

modules/gitbox/files/bin/git-settings.py
add script for bulk import/export of settings
=> add script for bulk import/export of settings

data/nodes/whimsy-vm4.apache.org.yaml
=> Addition to PR530 - icla move

modules/gitbox/files/bin/git-settings.py
fix usage examples, indent json
=> fix usage examples, indent json

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
Added the download for maven, ant, nant, iedriver, chromedriver and setup symlinks. Needs some general cleanup and comments.
=> Added the download for maven, ant, nant, iedriver, chromedriver and setup symlinks. Needs some general cleanup and comments.

modules/gitbox/files/cgi-bin/sync-repo.cgi
use popen to catch errors, fix some wrong var names
=> use popen to catch errors, fix some wrong var names

modules/subversion_server/files/authorization/asf-authorization-template
INFRA-15434 - make trnk,tags,branches only r/o
=> INFRA-15434 - make trnk,tags,branches only r/o

modules/subversion_server/files/authorization/asf-mailer.conf
INFRA-15437: openwhisk private -> p@openwhisk.a.o
=> INFRA-15437: openwhisk private -> p@openwhisk.a.o

modules/loggy/files/loggy.py, modules/loggy/manifests/init.pp
=> bump bulk log size

modules/mboxer/files/tools/archive.py, modules/mboxer/files/tools/settings.yml, modules/mboxer/manifests/init.pp
Allow messages to be segregated into private/public.
=> Add private security realm

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/pit-authorization-template
Add royale auth from LDAP for purposes of a PMC area in svn. INFRA-15461
=> Add royale auth from LDAP for purposes of a PMC area in svn. INFRA-15461

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
Refactoring to make everything run in order.
=> Refactoring to make everything run in order.

data/nodes/themis.apache.org.yaml, data/nodes/tlp-eu-mid.apache.org.yaml, data/nodes/tlp-eu-new.apache.org.yaml, data/nodes/tlp-eu-west.apache.org.yaml
Adding includes for subversion-staging.apache.org
=> Adding includes for subversion-staging.apache.org

modules/build_slaves/manifests/jenkins.pp
installs latest version of 3.5, 4.3 and latest (which is 4.3.0-1) now
=> install different versions of gradle

data/nodes/jenkins-master.apache.org.yaml
fixing the logrotate location for catalina.out
=> fixing the logrotate location for catalina.out

modules/mail_archives/manifests/init.pp
=> remove leading bracket

modules/mboxer/manifests/init.pp
Treasurer, president, ea and secretary are all private
=> The non-test list aliases are all private

modules/mboxer/manifests/init.pp
Add missing aliases for vp-brand and vp-fundraising list aliases
=> vp-brand/vp-fundraising alias mail archives

modules/subversion_server/files/authorization/asf-authorization-template
More of Apache Directory moved to Git, make these area r/o. INFRA-15446
=> More of Apache Directory moved to Git, make these area r/o. INFRA-15446

modules/subversion_server/files/authorization/pit-authorization-template
=> Add kibble pmc area

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
Added cygwin download and install. Moved download code to download.pp and left zip extraction in install.pp
=> Added cygwin download and install. Moved download code to download.pp and left zip extraction in install.pp

environments/windows/modules/jenkins_slave_windows/manifests/install.pp
Removing a bunch of nonsense and adding in a create conditional for JDK packages.
=> Removing a bunch of nonsense and adding in a create conditional for JDK packages.

environments/windows/modules/jenkins_slave_windows/manifests/install.pp
Cleaning up all the other zip extracts.
=> Cleaning up all the other zip extracts.

modules/selfserve_portal/files/site/js/mailform.json
tweak SSP mail form regex for mods
=> tweak SSP mail form regex for mods

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp
Added install for CMake 3.7.2 and Visual Studio 2015 Community Edition
=> Added install for CMake 3.7.2 and Visual Studio 2015 Community Edition

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp
Fixing a typo in install.pp and adding full install to Visual Studio
=> Fixing a typo in install.pp and adding full install to Visual Studio

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp
Removing Visual Studio from the automated install.
=> Removing Visual Studio from the automated install.

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
Fixing CMake symlink creation.
=> Fixing CMake symlink creation.

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
=> Set longpaths in git to true.

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
Create short symlink to workspaces
=> Create short symlink to workspaces

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
INFRA-15589: Move zookeper to gitwcsub
=> INFRA-15589: Move zookeper to gitwcsub

modules/gitwcsub/files/config/gitwcsub.cfg
INFRA-15599: Add daffodil to gitwcsub
=> INFRA-15599: Add daffodil to gitwcsub

modules/subversion_server/files/authorization/pit-authorization-template
INFRA-15440: allow self-serve to update qmail files
=> INFRA-15440: allow self-serve to update qmail files

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
changing git config from exec to file resource
=> changing git config from exec to file resource

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
appending instead of overwriting the git config file
=> appending instead of overwriting the git config file

modules/ldapserver/manifests/install/ubuntu/1404.pp, modules/ldapserver/manifests/install/ubuntu/1604.pp, modules/ldapserver/templates/slapd.conf.erb
overlay to track sessions (temporary.) update cronjob to purge backups after 2 days to handle larger fizesize.
=> add maxsize parameter for accesslog configuration. update accesslog

modules/gitwcsub/files/config/gitwcsub.cfg
INFRA-15592: Move jspwiki site to gitbox
=> INFRA-15592: Move jspwiki site to gitbox

data/nodes/proxy1-us-mid.apache.org.yaml
=> replace aardvark on bz.a.o

environments/windows/modules/datadog_agent/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/init.pp
Cleaned up all the lint warnings
=> Cleaned up all the lint warnings

modules/gitbox/files/bin/generate-index.py
Default to project raw name, cased.
=> Default to project raw name, cased.

modules/selfserve_portal/files/site/js/selfserve.coffee, modules/selfserve_portal/files/site/js/selfserve.js
=> add html footer if set

modules/selfserve_portal/files/site/js/selfserve.coffee, modules/selfserve_portal/files/site/js/selfserve.js
=> use the right element

modules/selfserve_portal/files/site/js/mailform.json
=> fix wording

data/nodes/asf919.gq1.ygridcore.net.yaml, data/nodes/asf920.gq1.ygridcore.net.yaml, modules/gitwcsub/files/config/gitwcsub.cfg
also add blockdiag to git-websites nodes
=> INFRA-15709 plc4x gitpubsub

data/nodes/asf919.gq1.ygridcore.net.yaml, data/nodes/asf920.gq1.ygridcore.net.yaml
Installing packages as per Chris Dutz in the HipChat channel.
=> Installing packages as per Chris Dutz in the HipChat channel.

modules/gitbox/manifests/roleaccount.pp
=> needa define here

modules/mail_private/manifests/init.pp
=> Auto lint check and fix

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/init.pp
Added flashplayer download and also added email/username for git into system gitconfig
=> Added flashplayer download and also added email/username for git into system gitconfig

modules/aim_server/manifests/init.pp
aim fixes: add mod_headers, gunicorn binary
=> aim fixes: add mod_headers, gunicorn binary

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
=> Adding JDK10 ea37

data/nodes/themis.apache.org.yaml, data/nodes/tlp-eu-west.apache.org.yaml
make ssi work on https. INFRA-15752
=> make ssi work on https. INFRA-15752

modules/pad_asf/files/pads.cgi, modules/pad_asf/files/pads.ezt, modules/pad_asf/manifests/init.pp
page (over the placeholder)
* add a template for the above
* install the template, too
=> * add the real (python) script to read the list of pads and generate a

modules/subversion_server/files/authorization/asf-authorization-template
=> Make VCL rw

data/nodes/tlp-eu-west.apache.org.yaml
ditch ssl session cache for now, it may be hinky
=> ditch ssl session cache for now, it may be hinky

data/nodes/mailrelay1-us-west.apache.org.yaml
transport map is defined elsewhere already(?)
=> transport map is defined elsewhere already(?)

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp
=> Changed JRE to JDK

data/nodes/svn01-us-west.apache.org.yaml
=> Bumped nifi to 1.6GB

modules/gitbox/files/cgi-bin/issues.cgi
refactor, set isComment for _all_ comments
=> refactor, set isComment for _all_ comments

modules/gitwcsub/files/config/gitwcsub.cfg
=> Add skywalking to gitwcsub

data/ubuntu/1604.yaml
Update 1604 to recommended TLS specifications for httpd
=> Update 1604 to recommended TLS specifications for httpd

data/nodes/tools-vm.apache.org.yaml
=> Downgrade TLS for tools-vm

data/nodes/mergebot-vm2.apache.org.yaml
@clambertus please take a look :)
=> add libz-dev necessary for building beam-site

data/nodes/es1-eu-mid.apache.org.yaml, data/nodes/es2-eu-mid.apache.org.yaml
=> Add yaml for new ES nodes

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
Adding Gradle to the Windows Jenkins Nodes
=> Adding Gradle to the Windows Jenkins Nodes

data/nodes/es1-eu-mid.apache.org.yaml, data/nodes/es2-eu-mid.apache.org.yaml
nix this, not needed on 16.04 any longer AIUI
=> nix this, not needed on 16.04 any longer AIUI

data/nodes/es1-eu-mid.apache.org.yaml, modules/loggy/templates/loggy.cfg.erb
switch over loggy to new cluster
=> switch over loggy to new cluster

modules/gitbox/files/asfgit/hooks/pre_receive.py
@clambertus this should do it.
=> Add mergebot-vm2 to approved pushers to gitbox.

modules/gitbox/files/asfgit/hooks/pre_receive.py
@clambertus conditionals are hard yo
=> Add better mechanism for changing mergebot IPs

data/nodes/tools-vm.apache.org.yaml
=> Add serveraliases

modules/gitwcsub/files/app/gitwcsub.py
Accept $baseurl/repo:branch (thus allowing non-standard branches)
=> Accept $baseurl/repo:branch (thus allowing non-standard branches)

modules/gitwcsub/files/config/gitwcsub.cfg
Add ratis to gitwcsub, lint file
=> Add ratis to gitwcsub, lint file

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
INFRA-15871: Switch Cayenne to gitwcsub
=> INFRA-15871: Switch Cayenne to gitwcsub

data/nodes/proxy1-lw-eu.apache.org.yaml
=> Pointing to new server.

modules/gitwcsub/files/config/gitwcsub.cfg
=> moving juneau to gitbox

data/nodes/gitbox.apache.org.yaml, modules/gitbox/files/asfgit/hooks/pre_receive.py
Signed-off-by: Jason Kuster <jasonkuster@google.com>
@clambertus whenever you're ready. 😄
=> Remove IP addresses for mergebot-vm due to decommission

data/nodes/ofbiz-vm2.apache.org.yaml
Trying out a different command for LetsEncrypt renewal.
=> Trying out a different command for LetsEncrypt renewal.

data/nodes/ofbiz-vm2.apache.org.yaml
Moving to webroot work around.
=> Moving to webroot work around.

data/nodes/ofbiz-vm2.apache.org.yaml
Moving proxypass for letsencrypt up.
=> Moving proxypass for letsencrypt up.

data/nodes/ofbiz-vm2.apache.org.yaml
=> Fixing webroot_path

data/ubuntu/1404.yaml, data/ubuntu/1604.yaml
Adding a process check for puppet in Datadog.
=> Adding a process check for puppet in Datadog.

data/nodes/jenkins-master.apache.org.yaml, modules/fail2ban_asf/files/fail2ban/conf/filter.d/apache-jenkins.conf
Add filter and jail for apache jenkins api
=> Add filter and jail for apache jenkins api

data/nodes/tac-vm2.apache.org.yaml
=> Add psycopg2

data/nodes/tac-vm2.apache.org.yaml
=> Add postgres

data/nodes/tac-vm2.apache.org.yaml
=> specify django version as 1.3

data/nodes/tac-vm2.apache.org.yaml
=> typo sneaked in:

data/nodes/tac-vm2.apache.org.yaml
=> Extend postgres config

modules/svngit2jira/files/config/svngit2jira.cfg
=> Adding Impala trigger.

environments/windows/modules/jenkins_slave_windows/templates/settings.xml.erb
removing single quotes from the template
=> removing single quotes from the template

modules/fail2ban_asf/files/fail2ban/conf/filter.d/apache-jenkins.conf
tweak regex for crumbissuer, xml is valid also
=> tweak regex for crumbissuer, xml is valid also

modules/selfserve_portal/files/site/cgi-bin/createml.cgi, modules/selfserve_portal/files/site/js/mailform.json
Add option for expediting list creation (within 1 hour)
=> Add option for expediting list creation (within 1 hour)

modules/svngit2jira/files/config/svngit2jira.cfg
=> Adding the Kylin project

modules/gitbox/files/bin/generate-index.py
=> sort repos in static list

modules/gitbox/files/bin/generate-index.py
sort without .git extension, add later
=> sort without .git extension, add later

data/common.yaml
removing 14.04 boxes so all ldap is on 16.04.
=> remove ldap1-lw-us as replication peer

modules/vhosts_whimsy/README.md
Fix up the readme to use the geo LDAP hosts
=> LDAP goes geo

data/common.yaml
re-enabling Windows modules in common.
=> re-enabling Windows modules in common.

data/nodes/mailarchive-vm.apache.org.yaml
Magic for bugzilla posts to work
=> Magic for bugzilla posts to work

modules/gitwcsub/files/config/gitwcsub.cfg
INFRA-16137: Add nemo to gitwcsub
=> INFRA-16137: Add nemo to gitwcsub

data/nodes/mailarchive-vm.apache.org.yaml, modules/mail_archives/files/mbox-archives.conf
=> remove -new

data/nodes/mailprivate-vm.apache.org.yaml
=> Add two required modules

data/nodes/mailprivate-vm.apache.org.yaml
=> Add macro this way

data/nodes/gitbox.apache.org.yaml, modules/gitbox/files/matt/site/resync.cgi
Add resync page for easy booping of repos (for github+wcsub)
=> Add resync page for easy booping of repos (for github+wcsub)

modules/gitbox/files/cgi-bin/issues.cgi
Truncate PR-from-fork diff if it's too large
=> Truncate PR-from-fork diff if it's too large

data/nodes/tools-vm.apache.org.yaml, modules/selfserve_portal/files/tools/authz.lua
Rework authz a bit, require chair/member for SSP
=> Rework authz a bit, require chair/member for SSP

modules/subversion_server/files/authorization/asf-authorization-template
=> remove extra reference to ea auth group

modules/gitwcsub/files/config/gitwcsub.cfg
INFRA-16207: Add dubbo to gitwcsub
=> INFRA-16207: Add dubbo to gitwcsub

modules/aim_server/files/plugins/session.py
=> tweak wording

data/nodes/steve-vm.apache.org.yaml
=> lock it tight

modules/loggy/files/loggy.py
=> tweak index settings

data/nodes/es1-eu-mid.apache.org.yaml, data/nodes/es2-eu-mid.apache.org.yaml, modules/loggy/files/loggy.py
enforce shards/replicas in config
=> enforce shards/replicas in config

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/pit-authorization-template
=> Adding Ace to attic.

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/pit-authorization-template
Removing another reference to Ace
=> Removing another reference to Ace

data/nodes/git1-us-west.apache.org.yaml
Generat static repo list, like on gitbox
=> Generat static repo list, like on gitbox

modules/mail_private/templates/refresh-index.pl.erb
Various changes to simplify/tidy the code.
The only functional change is to skip files that don't match dddddd[.gz]
=> Fix refresh index

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
Adding JDK10 to Windows Jenkins build nodes.
=> Adding JDK10 to Windows Jenkins build nodes.

modules/selfserve/files/selfserve/templates/index.html, modules/selfserve/files/selfserve/templates/sendemail.html
Update text to include information about refiling an ICLA if access to
the email is lost.
=> INFRA-16263

data/nodes/mailarchive-vm.apache.org.yaml
Start with a single redirect
Also added some comments for later maintainers
=> Add trial redirect for argus => ranger

modules/subversion_server/files/authorization/pit-authorization-template
INFRA-16292: Add freemarker pmc space
=> INFRA-16292: Add freemarker pmc space

data/nodes/es1-eu-mid.apache.org.yaml
=> add cron for curating indices

data/nodes/mailarchive-vm.apache.org.yaml
Add renames for projects and lists
=> INFRA-15966 - renamed projects and lists

modules/gitbox/files/cgi-bin/issues.cgi
unicode-encode email subject for PRs
=> unicode-encode email subject for PRs

data/nodes/mailarchive-vm.apache.org.yaml
=> INFRA-15966 - renamed projects and lists (mail-archives)

modules/mail_archives/files/scripts/update-index-monthly
Also fixes misplaced exit statement
=> Infra 15754 - fix year end processing

modules/git_mirror_asf/files/bin/graduate-podling.py, modules/gitbox/files/bin/graduate-podling.py, modules/gitbox/files/matt/tools/ghadd.py, modules/gitbox/files/matt/tools/grouper.py, modules/rootbin_asf/files/bin/arc_summary.sh, modules/rootbin_asf/files/bin/fbsd_jail_create.sh, modules/rootbin_asf/files/bin/fbsd_mv_jail_zfs.sh, modules/rootbin_asf/files/bin/homedirs.sh, modules/selfserve/files/selfserve/lib/ezt.py
=> Propose quick fix pylint/typos

modules/build_slaves/manifests/jenkins.pp
Adding require apt get update to kick apt.
=> Adding require apt get update to kick apt.

modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
Adding one for buildbot as well
=> Adding one for buildbot as well

modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
Workaround to get apt to update on the build nodes.
=> Workaround to get apt to update on the build nodes.

modules/svnwcsub/files/svnwcsub.conf
switch wcsub location for maven and maven/doxia
=> INFRA-16088

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-16350

data/nodes/themis.apache.org.yaml, data/nodes/tlp-eu-west.apache.org.yaml
themis and tlp-eu-west have almost the same content.
To make it easier to compare them, it helps if the spacing and
ordering is the same.
No functional changes.
=> Synchronise layout

modules/mail_archives/files/scripts/update-index
See https://bz.apache.org/bugzilla/show_bug.cgi?id=62291
The corresponding monthly script does not have the customisation
=> Use local TZ

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/asf-mailer.conf
This is an attempt to retire the HTrace podling as per https://incubator.apache.org/guides/retirement.html
Please let me know if there are any issues with the PR, thank you.
=> Retire HTrace podling

modules/blogs_asf/templates/roller-custom.properties.erb
Adding users.ldap.autoProvision.enabled and setting to true as per the ticket.
=> Adding users.ldap.autoProvision.enabled and setting to true as per the ticket.

data/ubuntu/1404.yaml, data/ubuntu/1604.yaml
Using facter to get hostname for datadog.conf vs the dd-agent.
=> Using facter to get hostname for datadog.conf vs the dd-agent.

modules/fail2ban_asf/files/fail2ban/conf/filter.d/apache-jenkins.conf
=> allow preceding query args

data/nodes/proxy1-us-mid.apache.org.yaml
Bringing this inline with other proxy boxes.
=> Bringing this inline with other proxy boxes.

data/roles/tlpserver.yaml, hiera.yaml, modules/customfact/lib/facter/customfact.rb
Add machine roles to puppet, set up a tlpserver role
=> Add machine roles to puppet, set up a tlpserver role

hiera.yaml
=> do we need to root this?

modules/subversion_server/files/authorization/asf-authorization-template
Marking uima/uimafit and uima/uv3/uimafit-v3 read only for GitBox move INFRA-16347
=> Marking uima/uimafit and uima/uv3/uimafit-v3 read only for GitBox move INFRA-16347

modules/subversion_server/files/authorization/asf-authorization-template
Migrating common/proper/weaver to gitbox INFRA-16438
=> Migrating common/proper/weaver to gitbox INFRA-16438

data/roles/tlpserver.yaml
refactor all download scripts into one server-wide block.
=> refactor all download scripts into one server-wide block.

modules/gitwcsub/files/config/gitwcsub.cfg, modules/subversion_server/files/authorization/asf-authorization-template
Moving maven-site and maven-doxia-site to gitbox INFRA-16361
=> Moving maven-site and maven-doxia-site to gitbox INFRA-16361

data/roles/tlpserver.yaml
=> change log paths (again)

data/roles/tlpserver.yaml
Fix closer.lua path, cull all custom handlers
=> Fix closer.lua path, cull all custom handlers

data/roles/tlpserver.yaml
fix inheritance and path for mirror script
=> fix inheritance and path for mirror script

modules/gitwcsub/files/config/gitwcsub.cfg
Moving Drill to gitbox INFRA-16411
=> Moving Drill to gitbox INFRA-16411

data/nodes/rsync-eu-mid.apache.org
add yaml for new dedicated rsync server
=> add yaml for new dedicated rsync server

Puppetfile
we need 1.11+ for wstunnel support
=> upgrade apache puppet module

modules/rsync_mirror/manifests/init.pp
remove stale configs from rsync
=> remove stale configs from rsync

modules/rsync_mirror/manifests/init.pp
re-introduce rsync logs for henk
=> re-introduce rsync logs for henk

data/nodes/rsync-eu-mid.apache.org.yaml, modules/tlp_vhosts/manifests/compat.pp
Remove files that are now in svn
=> Remove files that are now in svn, add revision checks

modules/subversion_server/files/authorization/asf-authorization-template
marking myfaces/core read only for move to gitbox
=> marking myfaces/core read only for move to gitbox

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
Added ant 1.10.3 and rebuild the way the 'latest' sysmlinks are created and updated.
=> Added ant 1.10.3 and rebuild the way the 'latest' sysmlinks are created and updated.

modules/subversion_server/files/authorization/asf-authorization-template
@cthistle I've made the changes for myfaces-test
=> INFRA-16402 myfaces-test moved to gitbox

data/common.yaml
Adding customfact to classes_windows
=> Adding customfact to classes_windows

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
=> fixing path to latest symlink

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
Changing logic on symlink update
=> Changing logic on symlink update

modules/subversion_server/files/authorization/asf-authorization-template
=> No longer needed

modules/subversion_server/files/authorization/asf-authorization-template
@cthistle finished myfaces-build-tools
=> INFRA-16402 myfaces-build-tools moved to gitbox

modules/mysql_asf/manifests/backup.pp
Adjust DB backup time to later in the US afternoon to prevent
application blocking during db backups.
=> INFRA-16158

modules/subversion_server/files/authorization/asf-authorization-template
=> INFRA-15596

modules/cwiki_asf/templates/server.xml.erb
remove deprecated values minProcessors, maxProcessors, maxSpareaThreads
=> remove deprecated values minProcessors, maxProcessors, maxSpareaThreads

modules/postgresql_asf/manifests/backup.pp
boop the backup frequency to every 4 hours on prod jira
=> postgres backup frequency

modules/stunnel_asf/manifests/init.pp
=> mysql-rsync

data/nodes/bai.apache.org.yaml, data/nodes/mysql1-ec2-va.apache.org.yaml, data/nodes/mysql1-us-mid.priv.apache.org.yaml, data/nodes/mysql3-us-west.apache.org.yaml
rearrange target list and set backups for mysql1-us-mid (primary) rather than broken replica.
=> add remaining mysql boxes to perform rsync offsite backups

modules/kif/files/kif.py, modules/kif/templates/kif.yaml.erb
Update KIF, set no notify for loggy stuff.
=> Update KIF, set no notify for loggy stuff.

modules/buildbot_asf/files/configscanner.py
Allow script to work with older SVN client
=> Downdate SVN command

modules/buildbot_asf/files/configscanner.py
Sending of recovery email broke with the previous PR.
This should fix it.
=> Config email fix

modules/gitwcsub/files/config/gitwcsub.cfg
INFRA-16562: gitpubsub for heron
=> INFRA-16562: gitpubsub for heron

modules/qmail_asf/manifests/init.pp
Install couple of required packages to get started
=> Install couple of required packages to get started

modules/qmail_asf/manifests/init.pp
Add some more required packages.
=> Add some more required packages.

modules/svngit2jira/files/config/svngit2jira.cfg
=> INFRA-16538

modules/svnwcsub/files/svnwcsub.conf
Fix to drop duplicated entries
=> Infra 16576

data/nodes/es1-eu-mid.apache.org.yaml, data/nodes/es2-eu-mid.apache.org.yaml
Setting dns servers for each ES box
=> Setting dns servers for each ES box

data/nodes/tlp-eu-west.apache.org.yaml, data/roles/tlpserver.yaml
cleaning up resolv.conf on tlpserver role and tlp-eu
=> cleaning up resolv.conf on tlpserver role and tlp-eu

modules/ldapserver/manifests/install/ubuntu/ubuntu_1604.pp
switch tidy to mtime for ldap module
=> switch tidy to mtime for ldap module

data/nodes/mailarchive-vm.apache.org.yaml
Found some more renamed mailing lists
=> More renames

modules/customfact/lib/facter/customfact.rb
changed role to include new TLP box
=> changed role to include new TLP box

data/roles/tlpserver.yaml
adding a logrotate rule specific to the TLP log location
=> adding a logrotate rule specific to the TLP log location

data/nodes/repository-vm2.apache.org.yaml
removing log format that wasn't working and not needed
=> removing log format that wasn't working and not needed

data/nodes/repository-vm2.apache.org.yaml
=> removing combined env var

modules/svngit2jira/files/app/svngit2jira.py
INFRA-16642: Try to send regardless of unicode borks.
=> INFRA-16642: Try to send regardless of unicode borks.

modules/svngit2jira/files/svngit2jira.ubuntu
=> switch to py3 for svngit2jira

modules/gitbox/manifests/init.pp
slow down indexing so it doesn't back up.
=> slow down indexing so it doesn't back up.

modules/gitwcsub/files/config/gitwcsub.cfg
=> Move traffic control website

data/nodes/netbeans-vm.apache.org.yaml
Fixing incomplete path to the logfiles to be rotated by the logrotate
=> Logrotate config update - fix of the path to the logfile

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/asf-mailer.conf, modules/subversion_server/files/authorization/pit-authorization-template
=> INFRA-16568

modules/mboxer/manifests/init.pp
add exec to refresh aliases when the alias block changes
=> INFRA-15325

data/nodes/proxy1-us-west.apache.org.yaml
remove custom errordocs for reporter/projects/whimsy-old
=> INFRA-11154

modules/gitbox/files/matt/site/newrepo.cgi
allow any/all projects to use gitbox.
=> allow any/all projects to use gitbox.

data/roles/tlpserver.yaml
INFRA-16502: Add sponsor.a.o redirect
=> INFRA-16502: Add sponsor.a.o redirect

modules/svnwcsub/files/svnwcsub.conf
INFRA-16510: Remove retired podling pubsubs
=> INFRA-16510: Remove retired podling pubsubs

modules/gitbox/files/cgi-bin/issues.cgi, modules/svnwcsub/files/svnwcsub.conf
INFRA-16366: Simplify/expand emails to note comments created/edited/deleted
=> INFRA-16366: Simplify/expand emails to note comments created/edited/deleted

data/roles/tlpserver.yaml
removing incubator rewrite on freemarker.a.o
=> removing incubator rewrite on freemarker.a.o

modules/selfserve_portal/files/site/cgi-bin/createml.cgi
=> no digest in list names

modules/subversion_server/files/authorization/asf-authorization-template
set geronimo/components/config R/O in preparation for gitbox move
=> INFRA-16614

modules/svnwcsub/files/svnwcsub.conf
staged changes for moving components svn loc from CMS area to project
repo
=> INFRA-16467

modules/gitbox/files/asfgit/git_multimail.py
INFRA-15680: Remove weird footer
=> INFRA-15680: Remove weird footer

data/nodes/ooo-forums3-vm.apache.org.yaml
=> update docroot for forums

modules/subversion_server/files/authorization/asf-mailer.conf
website contains content and components directories now
=> INFRA-16467 send all website html updates to site-commits

data/colo/dd_autotag_colo/aws.yaml, data/colo/dd_autotag_colo/azure.yaml, data/colo/dd_autotag_colo/google.yaml, data/colo/dd_autotag_colo/hetzner.yaml, data/colo/dd_autotag_colo/leaseweb_eu.yaml, data/colo/dd_autotag_colo/leaseweb_us.yaml, data/colo/dd_autotag_colo/online.net.yaml, data/colo/dd_autotag_colo/osu.yaml, data/colo/dd_autotag_colo/pnap.yaml, data/colo/dd_autotag_colo/rackspace.yaml, data/colo/dd_autotag_colo/yahoo.yaml, data/colo/lw-us.yaml, hiera.yaml, modules/customfact/lib/facter/customfact.rb
Autotaging host in datadog based on external IP
=> Autotaging host in datadog based on external IP

modules/svngit2jira/files/app/svngit2jira.py
note when a pubsub client thread dies
=> note when a pubsub client thread dies

modules/gitwcsub/files/config/gitwcsub.cfg
Add pubsub publish for ozone.hadoop.a.o per INFRA-16457
=> gitwcsub update

data/roles/tlpserver.yaml
accept multipart subdomains on tlp servers
=> accept multipart subdomains on tlp servers

data/nodes/gitbox.apache.org.yaml
Less frequent cronjobs till we fix rate limiting (+ lint fix)
=> Less frequent cronjobs till we fix rate limiting (+ lint fix)

modules/customfact/lib/facter/customfact.rb
removing the need for DNS, should get local external IP
=> removing the need for DNS, should get local external IP

environments/windows/modules/customfact/lib/facter/customfact.rb
updating Windows customfact with latest changes
=> updating Windows customfact with latest changes

modules/gitbox/files/gitweb/gitweb.css
changing css to fix jenky image INFRA-16619
=> changing css to fix jenky image INFRA-16619

modules/mail_archives/files/scripts/site-index.py, modules/mail_archives/files/scripts/update-index, modules/mail_archives/manifests/init.pp
INFRA-16691: Only write to index.html on success
=> INFRA-16691: Only write to index.html on success

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
=> Gm/jdk11 ea+19

environments/windows/modules/jenkins_slave_windows/manifests/download.pp
https was causing some powershell issues
=> https was causing some powershell issues

data/nodes/projects-vm2.apache.org.yaml
copy projects-vm to projects-vm2 to prepare for migration
=> INFRA-16653

data/nodes/asf-bz1-us-mid.priv.apache.org.yaml
=> adding kif to bz

data/nodes/ooo-wiki3-vm.apache.org.yaml
copy httpd config from old box, add memcached
=> ooo-wiki3-vm

modules/bb_pip_asf/files/configscanner.py, modules/bb_pip_asf/files/configscanner.ubuntu, modules/bb_pip_asf/manifests/init.pp
once more; tweak cfgscanner to systemd service, run in foreground and log borks
=> once more; tweak cfgscanner to systemd service, run in foreground and log borks

modules/bb_pip_asf/manifests/init.pp
=> fix service file path

modules/bb_pip_asf/files/configscanner.ubuntu
use bash to run a series of commands
=> use bash to run a series of commands

data/nodes/gitbox.apache.org.yaml
add private area for private git repos
=> add private area for private git repos

modules/projects_pvm_asf/manifests/init.pp
Need to log what stderr is seeing ...
=> Capture stderr as well

modules/subversion_server/files/authorization/asf-authorization-template
INFRA-16738: Keep httpasyncclient read/write
=> INFRA-16738: Keep httpasyncclient read/write

modules/gitwcsub/files/config/gitwcsub.cfg
=> moving flink-web to gitbox

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
Add Maven 3.5.4 , Ant 1.10.5 , Ant 1.9.13, JDK 11 ea+23 to Windows build nodes
=> Add Maven 3.5.4 , Ant 1.10.5 , Ant 1.9.13, JDK 11 ea+23 to Windows build nodes

modules/selfserve_portal/files/site/git.html
=> git-wip EOL'ed, use gitbox.

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp
Moving install files, fixing busted symlinks and busted symlink updating
=> Moving install files, fixing busted symlinks and busted symlink updating

data/roles/jenkins-external.yaml, data/roles/jenkins.yaml
adding monitoring tags to Jenkins nodes
=> adding monitoring tags to Jenkins nodes

modules/jenkins_asf/files/trim-workspace-all-jobs.sh
syntax, add continuation slash. Remove prune, we are already using -delete
=> syntax, add continuation slash. Remove prune, we are already using -delete

modules/gitwcsub/files/config/gitwcsub.cfg
migrating Mesos to GitBox INFRA-16832
=> migrating Mesos to GitBox INFRA-16832

modules/build_slaves/manifests/snapcraft.pp
reverse logic, create group first.
=> reverse logic, create group first.

modules/build_slaves/manifests/snapcraft.pp
dont fail a puppet run , just warn
=> dont fail a puppet run , just warn

modules/build_slaves/manifests/snapcraft.pp
add refreshonly to chown and init. lint fixes alignment
=> add refreshonly to chown and init. lint fixes alignment

data/roles/tlpserver.yaml
Redirect quarks -> edgent and distributedlog -> bookkeeper as per INFRA-16302
=> Redirect quarks -> edgent and distributedlog -> bookkeeper as per INFRA-16302

data/nodes/asf929.gq1.ygridcore.net.yaml, data/nodes/pietas.apache.org.yaml, data/roles/jenkins.yaml
enable snapcraft, class only runs when on 1604 nodes
=> enable snapcraft, class only runs when on 1604 nodes

modules/jenkins_asf/manifests/init.pp, modules/jenkins_asf/templates/node-config.xml.erb
iterate and populate each win node
=> iterate and populate each win node

modules/jenkins_asf/manifests/init.pp
=> scoping inside a define

modules/gitbox/files/cgi-bin/sync-repo.cgi
lint and make sub-sections work
=> lint and make sub-sections work

modules/subversion_server/files/authorization/asf-authorization-template
per chair, return r/w access to /sis repos. access limited to PMC
=> INFRA-16930

data/nodes/allura-vm2.apache.org.yaml, data/nodes/any23-vm2.apache.org.yaml, data/nodes/archiva-vm2.apache.org.yaml, data/nodes/cocoon-vm.apache.org.yaml, data/nodes/cordova-vm.apache.org.yaml, data/nodes/couchdb-vm2.apache.org.yaml, data/nodes/drat-vm.apache.org.yaml, data/nodes/forrest-vm.apache.org.yaml, data/nodes/freemarker-vm.apache.org.yaml, data/nodes/jena-vm.apache.org.yaml, data/nodes/netbeans-vm.apache.org.yaml, data/nodes/ocw-vm.apache.org.yaml, data/nodes/ofbiz-vm2.apache.org.yaml, data/nodes/ooo-forums3-vm.apache.org.yaml, data/nodes/ooo-wiki3-vm.apache.org.yaml, data/nodes/openmeetings-vm2.apache.org.yaml, data/nodes/plc4x-vm.apache.org.yaml, data/nodes/ponymail-vm.apache.org.yaml, data/nodes/sensoft-vm.apache.org.yaml, data/nodes/struts-vm.apache.org.yaml, data/nodes/syncope-vm2.apache.org.yaml, data/nodes/taverna-vm.apache.org.yaml, data/nodes/tobago-vm.apache.org.yaml, data/nodes/whimsy-vm4.apache.org.yaml, data/nodes/wicket-vm.apache.org.yaml, data/roles/jenkins-external.yaml, data/roles/jenkins.yaml, data/roles/tlpserver.yaml
adding DD tagging to tlp role,jenkins role, and project VMs
=> adding DD tagging to tlp role,jenkins role, and project VMs

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-16964

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
adding jdk11-ea+28 to the Windows nodes for INFRA-16952
=> adding jdk11-ea+28 to the Windows nodes for INFRA-16952

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
changing the timing from 15 mins to 60 mins.
=> changing the timing from 15 mins to 60 mins.

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
moving from svnwcsub to gitwcsub
=> moving from svnwcsub to gitwcsub

modules/asful/files/webstats-domains.txt, modules/asful/files/webstats.py, modules/asful/manifests/init.pp
=> linting for webstats program

modules/webstats/files/webstats-domains.txt
adding jmeter.a.o to stats export INFRA-15406
=> adding jmeter.a.o to stats export INFRA-15406

modules/jenkins_asf/templates/node-config.xml.erb
adding percent sign to PATH env var
=> adding percent sign to PATH env var

data/nodes/logging1-he-fi.apache.org.yaml, data/nodes/logging2-he-fi.apache.org.yaml
=> add new logging servers

data/nodes/logging1-he-fi.apache.org.yaml, data/nodes/logging2-he-fi.apache.org.yaml
=> pin ES to 5.6.11 instead

modules/webstats/files/webstats.py
refactor code, add top referrers (without divulging too much)
=> refactor code, add top referrers (without divulging too much)

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-16996

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-17039

modules/qmail_asf/manifests/init.pp, modules/qmail_asf/templates/ezmlmrc.erb
=> Add .ezmlmrc config file

modules/gitwcsub/files/config/gitwcsub.cfg
add a staging path for the camel-website git repo testing
=> INFRA-15969

data/nodes/memnon.apache.org.yaml
Fix content-type for signature files
=> INFRA-17067

modules/build_slaves/manifests/jenkins.pp
add a tidy for jenkins slaves to clean up wayward *ws-cleanup* dirs
=> jenkins diskspace issues

data/nodes/tools-vm.apache.org.yaml, data/nodes/tools-vm2.apache.org.yaml
moving from tools-vm to tools-vm2
=> moving from tools-vm to tools-vm2

modules/loggy/templates/loggy.cfg.erb
this needs to be an array not a var, I guess
=> this needs to be an array not a var, I guess

modules/loggy/templates/loggy.cfg.erb
=> only include tags with a : in

modules/loggy/files/loggy.py
always force bytes to be a number
=> always force bytes to be a number

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
=> INFRA-16931

modules/customfact/lib/facter/customfact.rb
=> adding lucene to customfact

modules/subversion_server/files/authorization/asf-authorization-template
INFRA-17141: move openjpa to gitbox
=> INFRA-17141: move openjpa to gitbox

modules/tlp_vhosts/files/dist/.htaccess
=> hpp-dist-htaccess

data/nodes/svn01-us-west.apache.org.yaml
Increase pulsar dist/dev limit to 450MB.
=> INFRA-17151

modules/gitbox/files/matt/tools/grouper.py
this is so we can uniformly analyze what goes on and react to rate limit and spam detection.
=> refactor gitbox grouper and add separate JSON fetching function

data/nodes/gitbox.apache.org.yaml, data/nodes/tools-vm.apache.org.yaml, modules/selfserve_portal/files/site/index.html
redirecting create git repo to gitbox
=> redirecting create git repo to gitbox

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-17169

modules/jenkins_asf/templates/node-config.xml.erb
adding TEMP and TMP to Windows Jenkins node env var
=> adding TEMP and TMP to Windows Jenkins node env var

modules/buildbot_slave/templates/buildslave.service.erb
=> tweaks because

modules/gitwcsub/files/config/gitwcsub.cfg
I think this is the right configuration. From GitBox repository `camel-website`'s `asf-site` branch to camel.apache.org/staging.
@clambertus can you take a look?
=> Update Camel staging site source

data/nodes/memnon.apache.org.yaml
=> adding blocky to memnon

data/nodes/jenkins02.apache.org.yaml
adding jenkins02 specific snmpd config
=> adding jenkins02 specific snmpd config

data/nodes/jenkins02.apache.org.yaml
adding the rest of the custom config
=> adding the rest of the custom config

modules/gitwcsub/files/config/gitwcsub.cfg
website TLP graduation for ServiceComb INFRA-17185
=> website TLP graduation for ServiceComb INFRA-17185

data/nodes/proxy1-lw-us.apache.org.yaml, data/nodes/roller-vm2.apache.org.yaml, modules/blogs_asf/manifests/init.pp
tweaks, add missing required perl packages, fix perms, change/add some httpd config options.
=> tweaks, add missing required perl packages, fix perms, change/add some httpd config options.

modules/buildbot_asf/files/buildbot.ubuntu
this fixes buildbot master restarting every 1 min
=> this fixes buildbot master restarting every 1 min

modules/blocky/manifests/init.pp
adding hourly restarts to blocky
=> adding hourly restarts to blocky

data/nodes/git1-us-east.apache.org.yaml, data/nodes/git1-us-west.apache.org.yaml, modules/git_mirror_asf/files/bin/update-index.sh, modules/git_mirror_asf/files/bin/update-mirror.sh
Part one of the automation setup;
- prep for running scripts/hooks
- do not update repos that have moved but retain a copy on git.a.o due to permission issues
=> Prep for Gitbox bulk automation

modules/blocky/files/blocky.py
=> adding full path to iptables

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-17308

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-17301

data/roles/tlpserver.yaml
=> INFRA-17359 - add Includes

modules/subversion_server/files/authorization/pit-authorization-template
=> Add treasurer group to financials

modules/gitwcsub/files/config/gitwcsub.cfg, modules/subversion_server/files/authorization/asf-authorization-template, modules/svnwcsub/files/svnwcsub.conf
Moving Archiva website to gitbox INFRA-16387
=> Moving Archiva website to gitbox INFRA-16387

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-17376

modules/qmail_asf/templates/makelist-apache.sh.erb
=> Fixup perms of newly created list INFRA-14471

modules/gitwcsub/files/config/gitwcsub.cfg
migrating to gitbox INFRA-17385
=> migrating to gitbox INFRA-17385

modules/gitbox/files/asfgit/auth.py
(meant for UCB on commons-*.git)
=> Allow for project-wide overrides in config

modules/cwiki_asf/templates/copy-intermediates.sh.erb
adding pdfexport to the copy task
=> adding pdfexport to the copy task

modules/selfserve_portal/files/site/cgi-bin/createconfluence.cgi, modules/svngit2jira/files/app/svngit2jira.py
=> removing email lookup in JIRA

data/nodes/gitbox.apache.org.yaml
=> adding kif to gitbox

modules/gitbox/files/cgi-bin/issues.cgi, modules/gitbox/files/cgi-bin/template-jira.ezt
Allow for custom EZT files to be used, use one for JIRAs
=> Allow for custom EZT files to be used, use one for JIRAs

modules/subversion_server/files/authorization/asf-authorization-template
temp add 3 folks so they can clean up tags
=> temp add 3 folks so they can clean up tags

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
Add Maven 3.6.0 and symlink as latest
=> Add Maven 3.6.0 and symlink as latest

modules/mail_private/files/index.html, modules/mail_private/files/pmc/index.html-template, modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/pit-authorization-template
remove tiles ldap. INFRA-17496
=> remove tiles ldap. INFRA-17496

modules/build_slaves/manifests/jenkins.pp
=> add symlink to IBM Latest 8

modules/subversion_server/files/hooks/buildbot_project_paths
=> missed a path

modules/svnqavm_pvm_asf/manifests/init.pp
For INFRA-17538 @Humbedooh 
The first of these cron jobs has been in place for some time. The second is new (it was finished yesterday), but I don't expect we'll need to change it (the PMC can just change the script the cron job invokes) so I'm PR'ing it now too.
Thanks.
=> INFRA-17538: Add cron jobs to svn-qavm3

data/nodes/roller-vm2.apache.org.yaml
updating to 5.2.2 as per INFRA-17603
=> updating to 5.2.2 as per INFRA-17603

modules/gitbox/files/bin/generate-index.py
this will be used for some statistics on the front page
=> Add commit count history fetching

modules/subversion_server/files/authorization/asf-mailer.conf
=> INFRA-17564

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
adding JDK12 ea27 and JDK13 ea3 to the Jenkins Windows nodes INFRA-17384
=> adding JDK12 ea27 and JDK13 ea3 to the Jenkins Windows nodes INFRA-17384

environments/windows/modules/datadog_agent/manifests/init.pp
Fixing the DD installer to a specific version
=> Fixing the DD installer to a specific version

modules/gitbox/files/cgi-bin/issues.cgi, modules/gitbox/files/cgi-bin/template.ezt
OF: Cleanups for github messages
=> OF: Cleanups for github messages

modules/gitbox/files/cgi-bin/issues.cgi
=> OF: wrong var

modules/gitbox/files/cgi-bin/template.ezt
OF: This should still be there
=> OF: This should still be there

modules/svngit2jira/files/config/svngit2jira.cfg
INFRA-17629: Add svngit2jira integration for Airflow
=> INFRA-17629: Add svngit2jira integration for Airflow

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/manifests/jenkins.pp
=> Add latest jbake. INFRA-17551

modules/gitwcsub/files/config/gitwcsub.cfg
=> INFRA-17665

modules/gitbox/files/asfgit/git_multimail.py, modules/gitbox/files/cgi-bin/issues.cgi, modules/gitbox/files/cgi-bin/sync-repo.cgi
Try to force a diff for distinct commits
=> Try to force a diff for distinct commits

modules/gitbox/files/asfgit/git_multimail.py
=> actually force diffs

modules/gitbox/files/cgi-bin/sync-repo.cgi
Don't default to force diff, only if commit array has distinct
=> Don't default to force diff, only if commit array has distinct

modules/gitbox/files/cgi-bin/sync-repo.cgi
disregard merge messages if head commit, they are always distinct
=> disregard merge messages if head commit, they are always distinct

modules/gitbox/files/cgi-bin/relay.cgi, modules/gitbox/files/conf/relay.yaml
Add a github webhook relay for projects
=> Add a github webhook relay for projects

modules/gitbox/files/cgi-bin/relay.cgi, modules/gitbox/files/conf/relay.yaml
enable sling webhooks for jenkins
=> enable sling webhooks for jenkins

modules/gitbox/files/cgi-bin/relay.cgi, modules/gitbox/files/conf/relay.yaml
=> add RTD hook for airavata

modules/gitbox/files/cgi-bin/relay.cgi
Fix request headers to appease Jenkins
=> Fix request headers to appease Jenkins

modules/gitbox/files/cgi-bin/relay.cgi
=> OF, import os, spit out RC

modules/selfserve_portal/files/site/cgi-bin/migratemoin.cgi, modules/selfserve_portal/files/site/index.html, modules/selfserve_portal/files/site/js/moinform.json, modules/selfserve_portal/files/site/moin.html
Add start of moin wiki migration selfserve tooling
=> Add start of moin wiki migration selfserve tooling

modules/subversion_server/files/authorization/pit-authorization-template
=> Perms for nemo ppmc svn area

modules/selfserve_portal/files/site/js/moinform.json
verify that a cwiki space exists before allowing the form to proceed
=> verify that a cwiki space exists before allowing the form to proceed

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/files/toolchains.xml, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp, modules/jenkins_asf/templates/node-config.xml.erb
=> Add jdks 12-ea+18 and 13-ea+4

data/nodes/netbeans-vm.apache.org.yaml
Fixing quotes of %{} in different places.
=> Fixing quote in rewrite rules

modules/buildbot_slave/files/toolchains.xml
=> add jdk13 to toolchains

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
adding JDK12_ea28 to the Jenkins Windows nodes
=> adding JDK12_ea28 to the Jenkins Windows nodes

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
adding Maven 3.6.0 to Jenkins Windows nodes INFRA-17706
=> adding Maven 3.6.0 to Jenkins Windows nodes INFRA-17706

data/nodes/proxy1-us-mid.apache.org.yaml, modules/httpd_rate_limiter/manifests/init.pp, modules/httpd_rate_limiter/templates/rate-limit.lua.erb
Add a rate limiting module to BZ for limiting CPU time per IP block
=> Add a rate limiting module to BZ for limiting CPU time per IP block

modules/httpd_rate_limiter/manifests/init.pp, modules/httpd_rate_limiter/templates/rate-limit.conf.erb
Add httpd_rate_limiter::autoconf for automatically configuring httpd
=> Add httpd_rate_limiter::autoconf for automatically configuring httpd

data/nodes/moin-vm.apache.org.yaml
=> autoconfig rate limiting

modules/httpd_rate_limiter/manifests/init.pp
=> OF: Fix syntax

modules/httpd_rate_limiter/manifests/init.pp
=> OF: fix definitions

modules/httpd_rate_limiter/manifests/init.pp
=> try conditional define?

data/nodes/moin-vm.apache.org.yaml
OF: Fix order, no need to declare lua specifically here
=> OF: Fix order, no need to declare lua specifically here

modules/kif/files/kif.py
=> Update KIF from upstream

modules/selfserve_portal/files/site/cgi-bin/migratemoin.cgi, modules/selfserve_portal/files/site/js/moinform.json, modules/selfserve_portal/files/site/moin.html
add option for importing full history of moin pages
=> add option for importing full history of moin pages

modules/selfserve_portal/files/sync-moin-all.sh, modules/selfserve_portal/files/sync-moin-project.sh, modules/selfserve_portal/manifests/init.pp
Add rsync scripts, add cronjob to runn -all , -project gets called per migration.
=> Add rsync scripts, add cronjob to runn -all , -project gets called per migration.

modules/selfserve_portal/files/exclude-list.txt, modules/selfserve_portal/files/sync-moin-all.sh, modules/selfserve_portal/files/sync-moin-project.sh, modules/selfserve_portal/manifests/init.pp
=> use a common exclude file

modules/selfserve_portal/files/converter.moinmoin.properties.template, modules/selfserve_portal/files/exporter.moinmoin.properties.template, modules/selfserve_portal/manifests/init.pp, modules/selfserve_portal/templates/confluenceSettings.properties.template.erb
=> Add some template files

data/nodes/jira-lw-us.apache.org.yaml
downsize httpd, we should never have to hit such high limits
=> downsize httpd, we should never have to hit such high limits

data/nodes/jira-lw-us.apache.org.yaml
=> Add rate limit

modules/selfserve_portal/files/exclude-list.txt
Add quite a few common files/dirs that we dont need to sysnc from moin
=> Add quite a few common files/dirs that we dont need to sysnc from moin

modules/selfserve_portal/files/www/site/css/default.css
Unfortunately box does not resize itself...
=> Allow extra space for the announce list name

modules/vhosts_whimsy/lib/puppet/parser/functions/preprocess_vhosts.rb
=> Use standard RO LDAP name

data/nodes/cwiki-vm3.apache.org.yaml, data/nodes/cwiki-vm4.apache.org.yaml
=> Add rate limiter to cwiki

data/nodes/cwiki-vm3.apache.org.yaml, data/nodes/cwiki-vm4.apache.org.yaml
=> add in base packages

data/nodes/cwiki-vm3.apache.org.yaml, data/nodes/cwiki-vm4.apache.org.yaml, modules/httpd_rate_limiter/manifests/init.pp, modules/httpd_rate_limiter/templates/rate-limit.lua.erb
=> whitelist synchrony for cwiki

modules/httpd_rate_limiter/templates/rate-limit.lua.erb
=> OF: typo, fixups

data/nodes/cwiki-vm4.apache.org.yaml
=> OF: syntaxo

data/nodes/cwiki-vm4.apache.org.yaml
=> Bump cpumax a bit

modules/httpd_rate_limiter/manifests/init.pp, modules/httpd_rate_limiter/templates/rate-limit-asfilter.conf.erb
implement rate limits as a filter for better TTFB measurements
=> implement rate limits as a filter for better TTFB measurements

data/nodes/jenkins-ubuntu3.apache.org.yaml, modules/build_slaves/manifests/multipy.pp
lets have allthepy , test on one node only for now
=> lets have allthepy , test on one node only for now

data/nodes/jenkins-ubuntu2.apache.org.yaml, modules/build_slaves/manifests/multipy.pp
have the required packages depend on the ppa and apt-update
=> have the required packages depend on the ppa and apt-update

modules/gitwcsub/files/config/gitwcsub.cfg
=> moving gobblin-site to gitbox

modules/gitbox/files/conf/auth.cfg
adding all commons repos to auth.cfg INFRA-17724
=> adding all commons repos to auth.cfg INFRA-17724

data/nodes/proxy1-us-mid.apache.org.yaml
=> tweaking the rate limit

data/colo/dd_autotag_colo/aws.yaml, data/colo/dd_autotag_colo/azure.yaml, data/colo/dd_autotag_colo/google.yaml, data/colo/dd_autotag_colo/hetzner.yaml, data/colo/dd_autotag_colo/leaseweb_eu.yaml, data/colo/dd_autotag_colo/leaseweb_us.yaml, data/colo/dd_autotag_colo/online.net.yaml, data/colo/dd_autotag_colo/osu.yaml, data/colo/dd_autotag_colo/pnap.yaml, data/colo/dd_autotag_colo/rackspace.yaml, data/colo/dd_autotag_colo/yahoo.yaml, data/common.yaml, hiera.yaml
=> cleaning up some dd_tagging

modules/gitbox/files/bin/authors.py, modules/gitbox/manifests/init.pp
Add authors.txt generator on gitbox
=> Add authors.txt generator on gitbox

modules/subversion_server/files/authorization/asf-mailer.conf
=> path change

data/ubuntu/ubuntu_1604.yaml, modules/customfact/lib/facter/customfact.rb
=> changing http request to follow redirects

modules/blogs_asf/files/themes/asffrontpage/searchresults.vm
removing searchdictionary as per INFRA-17850
=> removing searchdictionary as per INFRA-17850

modules/gitbox/files/cgi-bin/template-jira.ezt, modules/gitbox/files/cgi-bin/template.ezt
=> Missing word

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
update openjdk 12 and 13 to latest, symlink latest. INFRA-17904
=> update openjdk 12 and 13 to latest, symlink latest. INFRA-17904

modules/kif/files/kif.py
=> Merge KIF alerts into a single email, remove hipchat

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
adding latest JDK 12 and 13 versions to Windows build nodes
=> adding latest JDK 12 and 13 versions to Windows build nodes

modules/mail_archives/files/robots.txt
robots.txt is supposed to list all the sitemap index files; there are now two more
=> There are two more sitemap index files

data/common.yaml, modules/customfact/lib/facter/customfact.rb
adding external IP to DD tags for easier searching
=> adding external IP to DD tags for easier searching

data/nodes/logging1-he-fi.apache.org.yaml, data/nodes/logging2-he-fi.apache.org.yaml
=> making sure loggy is stopped

modules/blocky/files/blocky.py
checking if IP exists before doing more stuff
=> checking if IP exists before doing more stuff

modules/blocky/files/blocky.cfg, modules/blocky/files/blocky.py, modules/blocky/files/blocky.yaml, modules/blocky/manifests/init.pp
Replace blocky/1 with blocky/2 on all p3 boxes
=> Replace blocky/1 with blocky/2 on all p3 boxes

data/common.yaml
=> adding ubuntu version to tags

modules/blocky/files/blocky.py
Add IPv6 support, tweaks as per greg (version 2), fix stripping
=> Add IPv6 support, tweaks as per greg (version 2), fix stripping

data/ubuntu/ubuntu_1404.yaml
=> INFRA-17959

data/nodes/logging1-he-fi.apache.org.yaml, modules/blocky_server/manifests/init.pp
add blocky server class, fix httpd to use blocky/2, allow for public access to clients
=> add blocky server class, fix httpd to use blocky/2, allow for public access to clients

data/nodes/cwiki-vm4.apache.org.yaml
tweaking proxy settings for cwiki to fix 503s
=> tweaking proxy settings for cwiki to fix 503s

modules/selfserve/files/selfserve/lib/selfserve/__init__.py, modules/selfserve/files/selfserve/templates/changedetails.html
fix id.a.o to allow editing of empty attributes where the attribute is
marked editable and not multi
=> INFRA-9250

modules/subversion_server/files/authorization/pit-authorization-template
switch tac to attr=owner format
review requested for @gmcdonald
=> INFRA-16188

modules/subversion_server/files/authorization/asf-authorization-template
moving aries to gitbox INFRA-17806
=> moving aries to gitbox INFRA-17806

modules/gitbox/files/conf/auth.cfg, modules/selfserve_portal/files/www/site/cgi-bin/createml.cgi, modules/subversion_server/files/authorization/generate-dist-authorization
adding new folks to various other places
=> adding new folks to various other places

modules/jira_slack_bridge/files/slackbridge.yaml
Added jira notifications for the NEMO project to ASF slack channel #nemo-notifications
=> INFRA-18055

modules/selfserve/files/selfserve/lib/selfserve/__init__.py, modules/selfserve/files/selfserve/templates/changedetails.html
Reverts apache/infrastructure-puppet#1475
This change caused unexpected issues with the <not present> text
=> Revert "INFRA-9250"

modules/gitbox/files/asfgit/git_multimail.py
Reverts apache/infrastructure-puppet#1489
=> Revert "Added link to view commit diff online"

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
adding gpg4win to windows nodes INFRA-18014
=> adding gpg4win to windows nodes INFRA-18014

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
fixing a directory that I had incomplete and reformatting the line
=> fixing a directory that I had incomplete and reformatting the line

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
=> yet another formatting fix

modules/jenkins_asf/templates/node-config.xml.erb
=> adding gpg4win to path

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml
Add graphviz to all jenkins nodes. INFRA-17902
=> Add graphviz to all jenkins nodes. INFRA-17902

modules/selfserve_portal/files/www/site/cgi-bin/migratemoin.cgi, modules/selfserve_portal/files/www/site/js/moinform.json
Add dash for moin projects such as xmlgraphic-batik etc , fix for INFRA-17949
=> Add dash for moin projects such as xmlgraphic-batik etc , fix for INFRA-17949

modules/subversion_server/files/authorization/asf-mailer.conf
added polygene to the subversion_server/files/authorization/asf-mailer.conf.
=> Attic polygene

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
Added activemq-website to gitwcsub, Removed activemq-website from svnwcsub
=> Added activemq-website to gitwcsub

data/nodes/jenkins-websites1.apache.org.yaml
Add build deps required by Heron
=> Add build deps required by Heron

data/roles/jenkins-external.yaml, data/roles/jenkins-win.yaml, data/roles/jenkins.yaml
adding monitor tag to exclude build nodes from noisy monitors
=> adding monitor tag to exclude build nodes from noisy monitors

data/nodes/tools-vm.apache.org.yaml, modules/selfserve_portal/files/www/site/cgi-bin/createjira.cgi, modules/selfserve_portal/files/www/site/cgi-bin/sscommon.py
=> update to 8.4.0

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/mysql_asf/manifests/backup.pp, modules/rsync_asf/manifests/init.pp
Adding monitor to rsync backups
=> Adding monitor to rsync backups

modules/mboxer/files/tools/archive.py
*** 
Ideally this patch should be committed over a month end to reduce the number of mailboxes that will have to be merged. 
i.e. at around midnight UTC on April 30th 
***
See INFRA-18153.
This patch removes the .incubator. segment from the directory name on mod_mbox so mail-box directory names don't change when podlings graduate.
=> Remove .incubator from directory name.

data/nodes/mailprivate-vm.apache.org.yaml
adding macromboxcommitters to p3
=> adding macromboxcommitters to p3

modules/whimsy_server/manifests/cronjobs.pp
Job to tidy old mail directories
=> Add monthly tidy job

modules/blocky_server/manifests/init.pp, modules/postgresql_asf/manifests/backup.pp
adding monitoring to psql backups
=> adding monitoring to psql backups

data/nodes/mailprivate-vm.apache.org.yaml
Update mailprivate to use new committers group
=> Get committers from ou=role group

environments/windows/modules/jenkins_slave_windows/manifests/params.pp
See https://maven.apache.org/docs/3.6.1/release-notes.html
Especially https://issues.apache.org/jira/browse/WAGON-537 is interesting, it'll speed up downloads and uploads a lot
=> Add Maven 3.6.1

modules/subversion_server/files/authorization/pit-authorization-template
=> Add netbeans LDAP group and /pmc/netbeans auth

modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/init.pp
bumping gradle version to 4.10.3 as 4.10.2 seems to have gone missing
=> bumping gradle version to 4.10.3 as 4.10.2 seems to have gone missing

modules/gitbox_syncer/files/gitbox-syncer.Ubuntu, modules/gitbox_syncer/files/gitbox-syncer.py, modules/gitbox_syncer/files/gitbox-syncer.yaml, modules/gitbox_syncer/files/github_sync.py, modules/gitbox_syncer/manifests/init.pp
deploying to p3 and gitbox for initial tests
=> Initial check-in of gitbox-syncer daemon

Puppetfile
this is an attempt to fix a strange metadata issue with the concat
module.
=> try bumping concat version

modules/subversion_server/templates/post-commit.erb
extract the project for the commit and use it in the fisheye hook
=> Fix for fisheye hook

environments/windows/modules/jenkins_slave_windows/templates/gitconfig.txt.erb
changing autocrlf to input INFRA-18383
=> changing autocrlf to input INFRA-18383

modules/subversion_server/files/authorization/pit-authorization-template
=> private svn area for weex

modules/selfserve_portal/files/moin-ro.sh, modules/selfserve_portal/files/www/site/cgi-bin/migratemoin.cgi, modules/selfserve_portal/files/www/site/js/moinform.json
enable form for marking moin wiki read only
=> enable form for marking moin wiki read only

modules/git_self_serve/files/index.html
Add descriptive text for universal commit bit
=> INFRA-17320

modules/gitbox/files/matt/site/newrepo.html
Not sure what happened, but the previous fix 
https://github.com/apache/infrastructure-puppet/pull/1571/
was to a another file with similar content (which also needed to be updated)
=> INFRA-17320 - apply the change to the correct file

data/nodes/buildbot-vm2.apache.org.yaml
=> adding blocky to buildbot-vm2

modules/mysql_asf/templates/dbsave_mysql.sh.erb, modules/postgresql_asf/templates/dbsave_postgres.sh.erb, modules/rsync_asf/templates/rsync-offsite.sh.erb
adding some error checking to the backup scripts
=> adding some error checking to the backup scripts

data/nodes/mysql3-us-west.apache.org.yaml
bumping mysqldump to get past a backup error
=> bumping mysqldump to get past a backup error

data/nodes/jira-lw-us.apache.org.yaml
adding the full path to exclude
=> adding the full path to exclude

modules/svngit2jira/files/config/svngit2jira.cfg
Probably could OF this, but first one so second set of eyes
=> INFRA-18539

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
=> add latest openjdk13 ea 23

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
=> Add openjdk13 build ea 25

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/files/toolchains.xml, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
=> Add openjdk 14 support

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/manifests/jenkins.pp
=> remove old dockers

modules/subversion_server/files/authorization/asf-authorization-template
=> moving to gitbox INFRA-18351

data/nodes/roller-vm2.apache.org.yaml
=> bumping roller version

data/nodes/spamd1-us-west.apache.org.yaml, data/nodes/spamd2-us-west.apache.org.yaml, data/nodes/spamd3-us-west.apache.org.yaml, data/nodes/spamd4-us-west.apache.org.yaml
force infratest domain to new mailgw01 host
=> clean up transport map & docs

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
Adding JDK13ea30 and JDK14ea6 to the Windows nodes
=> Adding JDK13ea30 and JDK14ea6 to the Windows nodes

modules/build_slaves/manifests/jenkins.pp
remove unwanted .mavenrc file. INFRA-18812
=> remove unwanted .mavenrc file. INFRA-18812

modules/subversion_server/files/authorization/asf-authorization-template, modules/subversion_server/files/authorization/pit-authorization-template
=> remove unused auth group

environments/windows/modules/jenkins_slave_windows/templates/gitconfig.txt.erb
reverting change of autocrlf as per INFRA-18763
=> reverting change of autocrlf as per INFRA-18763

modules/blogs_asf/templates/planet-custom.properties.erb, modules/blogs_asf/templates/web.xml.erb
=> update config to remove schemeenforcement

modules/buildbot_asf/files/projects/jmeter/create-jmeter-nightlies-index.sh
With our migration to gradle we have changed the names of the artifacts. Therefore the index script has to be changed as well.
Modernize the script a bit while we are at it anyway.
=> Jmeter nightly new layout

modules/gitbox/files/hooks/post-receive.d/15-asf-yaml.py
This is just a test for now, tests the presence and contents of .asf.yaml, borks if it can't parse it. if not present or empty, ignore the repo for now.
=> Add hook for .asf.yaml parsing

data/nodes/jenkins02.apache.org.yaml
setting catalina logs to compress
=> setting catalina logs to compress

data/nodes/whimsy-vm4.apache.org.yaml
=> adding blocky to whimsy

modules/asf_checkrootkit/manifests/init.pp
add exclusion for postfix port
force root@a.o as the email target
=> INFRA-18991

modules/loggy/files/loggy.py
As the subject says.
Also might be worth recording the modtime of the rsa_key file for later analysis by fps.py
=> loggy fails to close rsa_key.pub file

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
=> Add Maven 3.6.2

modules/loggy/files/loggy.py
removing the tag overrides for the TLP boxes
=> removing the tag overrides for the TLP boxes

data/common.yaml
removing the MOTD about doing do-release-upgrade
=> removing the MOTD about doing do-release-upgrade

modules/gitbox/files/asfgit/asfyaml.py
This change adds support for the "Merge button" settings in github admin page (to define which merge methods are supported from the github PR UI)
ps: I am not sure which branch should be used as a target branch, let me know if deployment is not the good one.
=> INFRA-19282. Support merge button settings in .asf.yaml

modules/ldapserver/templates/slapd.conf.erb
pushed to branch instead of OF.
=> Moved the rule down to prevent fail through issues

data/roles/tlpserver.yaml
enabling new httpd blocky on TLP servers
=> enabling new httpd blocky on TLP servers

modules/webstats/files/webstats.py
The first commit tidies up the code to minimise the number of ES searches
The second commit adds YAML output to correspond with the ODS output
=> Webstats tidy and add YAML output

data/roles/jenkins-external.yaml, data/roles/jenkins-win.yaml, data/roles/jenkins.yaml
=> puppet_version => puppetversion

modules/genmeta_ldap/files/refresh_meta.sh
INFRA-19486 generate cn=member,ou=meta containing memberUids from cn=member,ou=group.
=> Updated refresh_meta to also do cn=member,ou=meta

data/nodes/netbeans-vm.apache.org.yaml
Moving /pluginportal2 ProxyPass section to netbeans-vm-ssl
=> [INFRA-19541] Moving ProxyPass to the https section

data/nodes/mailarchive-vm.apache.org.yaml, data/nodes/mailprivate-vm.apache.org.yaml
Mesatee mails are now all available under teaclave
=> INFRA-19532 redirect mesatee => teaclave

modules/apmirror/manifests/init.pp
=> Ensure apmirror owns zzz dir in dist/

modules/httpd_blocky/files/blocky_check.lua
This is for when people go to www.a.o and find themselves blocked. this'll show their IP as well.
=> Add in IP address that was banned.

environments/windows/modules/jenkins_slave_windows/manifests/download.pp, environments/windows/modules/jenkins_slave_windows/manifests/install.pp
=> bumping cmake to 3.16.2

modules/ldapserver/files/default-slapd
the process hangs when exceeding maxfile default 1024
=> increase maxfiles for slapd

modules/genmeta_ldap/files/refresh_meta.sh
add authentication support for searching, force the use of ldap-master.
clean up long lones where possible
=> clean up and fix refresh-meta.sh

modules/gitbox/files/asfgit/asfyaml.py
updated asfyaml to have the jekyll (as well as the pelican) keywords for configuring the generation of static content sites.
=> Updated asfyaml to have a jekyll function

modules/gitbox/files/bin/attic-repos.py
I defined them in the script, trying to get it to attic the Ode repos.
=> Still haven't found where DEBUG and CONFIG were defined

data/roles/tlpserver.yaml
setting MaxConnectionsPerChild to 0
=> setting MaxConnectionsPerChild to 0

data/roles/tlpserver.yaml
matching up some settings with svn01
=> matching up some settings with svn01

data/roles/tlpserver.yaml
changing threadlimit to match threadsperchild
=> changing threadlimit to match threadsperchild

data/roles/tlpserver.yaml
=> change tlp mpm_event settings to match known good

data/roles/tlpserver.yaml
Reverts apache/infrastructure-puppet#1724
=> Revert "change tlp mpm_event settings to match known good"

data/nodes/buildbot-vm2.apache.org.yaml
custom 404 for each docs version, see INFRA-19845
=> custom 404 for each docs version, see INFRA-19845

data/nodes/jenkins02.apache.org.yaml, modules/jenkins_asf/templates/setenv.sh.erb
Removing trailing slash from proxypass INFRA-19891
=> Removing trailing slash from proxypass INFRA-19891

data/nodes/gitbox.apache.org.yaml
adding rewrites for INFRA-17956
=> adding rewrites for INFRA-17956

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
adding jdk15 ea13 to the Windows nodes INFRA-19671
=> adding jdk15 ea13 to the Windows nodes INFRA-19671

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/buildbot_slave/files/toolchains.xml, modules/buildbot_slave/manifests/buildbot.pp
Add openjdk15 support for buildbot etc
=> Add openjdk15 support for buildbot etc

modules/buildbot_slave/files/toolchains.xml
remove extra closing toolchain
=> remove extra closing toolchain

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/build_slaves/manifests/jenkins.pp, modules/buildbot_slave/manifests/buildbot.pp
=> Add openjdk 1.8 242

modules/gitwcsub/files/config/gitwcsub.cfg, modules/staged/files/staged.py
This changes pubsubs for gitwcsub and stageD (for .asf.yaml staging and publishing)
=> Change pubsub addresses

data/roles/tlpserver.yaml
Updating keepalive timeouts on TLP servers.
=> Updating keepalive timeouts on TLP servers.

data/common.yaml
try and avoid crashes from web scanners
=> change stunnel port

data/nodes/buildbot-vm2.apache.org.yaml
=> try it another way

data/nodes/netbeans-vm.apache.org.yaml
Hi,
This is to set up plugins.netbeans.apache.org in the NetBeans VM box.
I'd appreciate an expert review of the configuration file.
Thanks & kind regards,
Antonio
=> [INFRA-20090] plugins.netbeans.apache.org

data/nodes/netbeans-vm.apache.org.yaml
It seems /space/pp3/public is our new root directory. Who knew! :-)
=> [INFRA-20090] plugins.netbeans.apache.org directory

environments/windows/modules/jenkins_slave_windows/manifests/params.pp
based on https://github.com/apache/infrastructure-puppet/pull/1647
still same problems as described in https://issues.apache.org/jira/browse/INFRA-18990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/infrastructure-puppet/1742)
=> INFRA-19726 add Maven 3.6.3 to Jenkins Windows nodes

data/nodes/mailprivate-vm.apache.org.yaml
prc archives were moved to press@
Ensure old Permalinks continue to work
=> prc => press

modules/gitbox/files/asfgit/asfyaml.py
To be documented :)
This adds notification scheme settings via .asf.yaml for repositories.
They are validated, then saved to a yaml file on disk.
To-Do: Use these settings...
=> Add notification scheme setter

modules/mail_archives/files/scripts/setlock.pl, modules/mail_archives/manifests/init.pp
We don't want to wait forever for the lock when performing the hourly index
=> Setlock wait

modules/gitbox/files/asfgit/git_multimail.py
This will utilize notifications.yaml (as set by .asf.yaml) if present, otherwise fall back to git config values.
=> Start weaving in notifications.yaml in commit/issue mailers

data/nodes/gitbox.apache.org.yaml, modules/gitbox/files/cgi-bin/issues.cgi
This moves the mail and jira bits out of this script, punting it to the gitbox-mailer program
Do not merge till gitbox-mailer is ready (waiting on updates+ezt)
=> Move mail+jira out of this cgi and into gitbox-mailer

data/nodes/netbeans-vm.apache.org.yaml
Setting up a virtual web server for https://synergy.netbeans.apache.org
=> [INFRA-20127] synergy.netbeans.apache.org

data/nodes/netbeans-vm.apache.org.yaml
=> [INFRA-20127] - Web directory typo

data/roles/tlpserver.yaml
- Redirects for uimaFIT and Ruta documentation
=> [UIMA-6237] Remove old documentation from website

data/nodes/logging1-he-fi.apache.org.yaml, data/nodes/logging2-he-fi.apache.org.yaml
=> exclude /x1 elasticsearch repos from backuppc

environments/windows/modules/jenkins_slave_windows/manifests/init.pp
Puppet restarts a scheduled task instead of the agent INFRA-20417
=> Puppet restarts a scheduled task instead of the agent INFRA-20417

data/nodes/backup02-he-de.apache.org.yaml
troubleshooting lack of queueing problem, some hosts aren't getting
nightly incrementals
=> revert retention to defaults

data/roles/testing-host.yaml, modules/customfact/lib/facter/customfact.rb
adding a node role for test machines to be excluded from monitoring
=> adding a node role for test machines to be excluded from monitoring

modules/gitwcsub/files/config/gitwcsub.cfg, modules/svnwcsub/files/svnwcsub.conf
=> Move events.a.o from CMS to git repo

environments/windows/modules/jenkins_slave_windows/manifests/init.pp, environments/windows/modules/jenkins_slave_windows/manifests/params.pp
adding OpenJDK 252_b09 to match linux configs INFRA-20700
=> adding OpenJDK 252_b09 to match linux configs INFRA-20700

modules/gitbox/files/asfgit/asfyaml.py
Support GitHub Protection Branch settings
It would be nice to be able to enable and disable on branches the protection settings without submitting an INFRA ticket.
* Require to pull request reviews before merging
* Number of required review approvals
* Dismiss stale pull request approvals when new commits are pushed
* Require review from Code Owners
* Require status checks to pass before merging
* Require branches to be up to date before merging
* Context of a status check
* Require signed commits
* Include administrators
* Restrictions (Define what users, apps, and teams can push to the branch.)
The goal of this PR is to implement as many of the defined settings above as possible.
**PR does not implement:**
* Context of a status check
* Include administrators
* Restrictions
APIv3 Repo …
=> feat: support GH protected branches in .asf.yaml

modules/buildbot_asf/files/root.html, modules/buildbot_asf/templates/master.cfg.erb
These qnodes are gone, to be replaced with new ones
=> These qnodes are gone, to be replaced with new ones

modules/gitbox/files/asfgit/asfyaml.py
The previous auth method seems to have been completely disabled now.
=> Switch to using access token in request headers

data/nodes/community-vm.apache.org.yaml, data/nodes/ponymail-vm.apache.org.yaml, data/nodes/steve-vm.apache.org.yaml
enable end-to-end encryption
switch config to use mail-relay cname as mailrelay1-lw-us is going away
=> switch to mail-relay and enable TLS

environments/windows/modules/jenkins_node_windows/manifests/init.pp, environments/windows/modules/jenkins_node_windows/manifests/params.pp
=> Add openjdk as latest16

modules/gitwcsub/files/config/gitwcsub.cfg
=> tvm is graduating INFRA-21122

data/ubuntu/ubuntu_1404.yaml, data/ubuntu/ubuntu_1604.yaml, data/ubuntu/ubuntu_1804.yaml, modules/buildbot_node/manifests/buildbot.pp
=> Add adoptopenjdk 11

modules/gitwcsub/files/config/gitwcsub.cfg
Not sure if this exactly what is needed, but it looks right.  I'm doing this to save you time so we can get this done before the new year!
Please pull ASAP so we can announce the release.  Whatever else needs to be done to update the website.
Happy new year!
=> INFRA-21250 rya-site project website: remove incubator from name

modules/gitwcsub/files/config/gitwcsub.cfg
Changes in P6 not applied here:
https://github.com/apache/infrastructure-p6/commit/0c13344bd5a09b7a1327a75dd92f0da2224946e0#diff-8ad59a092935e68445eb2bb2eeb2ac161aa47a490fb64327b272e6b7a3132a33
https://github.com/apache/infrastructure-p6/commit/3e32ed314647500ccc8f1d239c39aed39923b2a3#diff-8ad59a092935e68445eb2bb2eeb2ac161aa47a490fb64327b272e6b7a3132a33
https://github.com/apache/infrastructure-p6/commit/057b5db088165fe641314844849d2bfa53e189ed#diff-8ad59a092935e68445eb2bb2eeb2ac161aa47a490fb64327b272e6b7a3132a33
=> Apply changes from P6: ratis, goblin, daffodil

modules/gitbox/files/cgi-bin/template-jira.ezt, modules/gitbox/files/cgi-bin/template.ezt, modules/gitbox_mailer/files/email_template.ezt
The standard sig marker is dash-dash-space
=> Fix sig-markers

modules/gitbox/files/asfgit/git_multimail.py
https://github.com/git-multimail/git-multimail/commit/7b48e4fe110cd410fc5043dd44004b2a0c51a032
=> Fix old bug

modules/gitbox/files/asfgit/git_multimail.py
https://github.com/git-multimail/git-multimail/commit/ddc9a1c
=> Don't use the deprecated cgi.escape for Python 3

modules/gitbox/files/bin/attic-repos.py
no more programmatic renames for attic repos.
=> removed renaming bits from attic-repo.py script

modules/gitbox/files/bin/attic-repos.py
updates the description and creates a nocommit file for the repo.
=> Description update and nocommit file for attic-repos script

modules/gitbox_mailer/files/email_template.ezt, modules/gitbox_mailer/files/gitbox-mailer.py
Add info on how to unsubscribe
=> add unsub note
